.TH "_Device_cb" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Device_cb
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t(* \fBInit\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, uint8_t cfgidx)"
.br
.ti -1c
.RI "uint8_t(* \fBDeInit\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, uint8_t cfgidx)"
.br
.ti -1c
.RI "uint8_t(* \fBSetup\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, \fBUSBD_SetupReqTypedef\fP *req)"
.br
.ti -1c
.RI "uint8_t(* \fBEP0_TxSent\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev)"
.br
.ti -1c
.RI "uint8_t(* \fBEP0_RxReady\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev)"
.br
.ti -1c
.RI "uint8_t(* \fBDataIn\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, uint8_t epnum)"
.br
.ti -1c
.RI "uint8_t(* \fBDataOut\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, uint8_t epnum)"
.br
.ti -1c
.RI "uint8_t(* \fBSOF\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev)"
.br
.ti -1c
.RI "uint8_t(* \fBIsoINIncomplete\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, uint8_t epnum)"
.br
.ti -1c
.RI "uint8_t(* \fBIsoOUTIncomplete\fP )(struct \fB_USBD_HandleTypeDef\fP *pdev, uint8_t epnum)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetHSConfigDescriptor\fP )(uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetFSConfigDescriptor\fP )(uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetOtherSpeedConfigDescriptor\fP )(uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetDeviceQualifierDescriptor\fP )(uint16_t *length)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
