.TH "_USBD_CDC_Itf" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USBD_CDC_Itf
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t(* \fBInit\fP )(void)"
.br
.ti -1c
.RI "int8_t(* \fBDeInit\fP )(void)"
.br
.ti -1c
.RI "int8_t(* \fBControl\fP )(uint8_t cmd, uint8_t *pbuf, uint16_t length)"
.br
.ti -1c
.RI "int8_t(* \fBReceive\fP )(uint8_t *Buf, uint32_t *Len)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
