.TH "ADC_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_TypeDef \- Analog to Digital Converter 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSMPR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSMPR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSQR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSQR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSQR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJSQR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Analog to Digital Converter 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
