.TH "Inc/buzzer.h" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/buzzer.h \- Header for \fBbuzzer\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBUZZER_init\fP (void)"
.br
.RI "Инциализация модуля управления основным питанием\&. "
.ti -1c
.RI "void \fBBUZZER_set\fP (void)"
.br
.RI "Инциализация модуля управления основным питанием\&. "
.ti -1c
.RI "void \fBBUZZER_reset\fP (void)"
.br
.RI "Инциализация модуля управления основным питанием\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header for \fBbuzzer\&.c\fP file\&. 

Buzzer control module (Header file)\&. 
.PP
\fBAuthor\fP
.RS 4
Arthur Markaryan 
.RE
.PP
\fBDate\fP
.RS 4
26\&.03\&.2021 \\copiright 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void BUZZER_init (void)"

.PP
Инциализация модуля управления основным питанием\&. Функция инициализации модуля управления основным питанием\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "void BUZZER_reset (void)"

.PP
Инциализация модуля управления основным питанием\&. Функция инициализации модуля управления основным питанием\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "void BUZZER_set (void)"

.PP
Инциализация модуля управления основным питанием\&. Функция инициализации модуля управления основным питанием\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
