.TH "CMSIS_Core_SysTickFunctions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_SysTickFunctions \- SysTick Functions
.PP
 \- Functions that configure the System\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBITM Functions\fP"
.br
.RI "Functions that access the ITM debug interface\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBISER\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBICER\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRSERVED1\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBISPR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBICPR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBIABR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBITNS\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBIPR\fP [124U]"
.br
.ti -1c
.RI "__IM uint32_t \fBCPUID\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBICSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBAIRCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSHPR\fP [2U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSHCSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCTRL\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBLOAD\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBVAL\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCALIB\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCTRL\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [6U]"
.br
.ti -1c
.RI "__IM uint32_t \fBPCSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP3\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION3\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED8\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP4\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED9\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION4\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED10\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP5\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED11\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION5\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED12\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP6\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED13\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION6\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED14\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP7\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED15\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION7\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED16\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP8\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED17\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION8\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED18\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP9\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED19\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION9\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED20\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP10\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED21\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION10\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED22\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP11\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED23\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION11\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED24\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP12\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED25\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION12\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED26\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP13\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED27\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION13\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED28\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP14\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED29\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION14\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED30\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP15\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED31\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION15\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBSSPSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCSPSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBACPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [55U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSPPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [131U]"
.br
.ti -1c
.RI "__IM uint32_t \fBFFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBFFCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBPSCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [809U]"
.br
.ti -1c
.RI "__OM uint32_t \fBLAR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBLSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [4U]"
.br
.ti -1c
.RI "__IM uint32_t \fBTYPE\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVTYPE\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDHCSR\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCRSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDCRDR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDEMCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBDAUTHCTRL\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDSCSR\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBIP\fP [8U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSHP\fP [2U]"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBTRIGGER\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITFTTD0\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBITATBCTR2\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITATBCTR0\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITFTTD1\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBITCTRL\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [39U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCLAIMSET\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCLAIMCLR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [8U]"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVID\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSFCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions that configure the System\&. 


.SH "Variable Documentation"
.PP 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved
.PP
bit: 0\&.\&.15 Reserved
.PP
bit: 0\&.\&.26 Reserved 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved
.PP
bit: 9\&.\&.15 Reserved
.PP
bit: 9 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved 
.SS "uint32_t _reserved0"
bit: 0 Reserved
.PP
bit: 3\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 0 Reserved 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved 
.SS "uint32_t _reserved0"
bit: 0 Reserved 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "uint32_t _reserved0"
bit: 9\&.\&.23 Reserved 
.SS "uint32_t _reserved0"
bit: 0 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved
.PP
bit: 20\&.\&.23 Reserved
.PP
bit: 16\&.\&.23 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved
.PP
bit: 4\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 25\&.\&.27 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved 
.SS "__IOM uint32_t ACPR"
Offset: 0x010 (R/W) Asynchronous Clock Prescaler Register 
.SS "__IOM uint32_t AIRCR"
Offset: 0x00C (R/W) Application Interrupt and Reset Control Register 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }  b"
Structure used for bit access 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "__IM uint32_t CALIB"
Offset: 0x00C (R/ ) SysTick Calibration Register 
.SS "__IOM uint32_t CCR"
Offset: 0x014 (R/W) Configuration Control Register 
.SS "__IOM uint32_t CLAIMCLR"
Offset: 0xFA4 (R/W) Claim tag clear 
.SS "__IOM uint32_t CLAIMSET"
Offset: 0xFA0 (R/W) Claim tag set 
.SS "__IOM uint32_t COMP0"
Offset: 0x020 (R/W) Comparator Register 0 
.SS "__IOM uint32_t COMP1"
Offset: 0x030 (R/W) Comparator Register 1 
.SS "__IOM uint32_t COMP10"
Offset: 0x0C0 (R/W) Comparator Register 10 
.SS "__IOM uint32_t COMP11"
Offset: 0x0D0 (R/W) Comparator Register 11 
.SS "__IOM uint32_t COMP12"
Offset: 0x0E0 (R/W) Comparator Register 12 
.SS "__IOM uint32_t COMP13"
Offset: 0x0F0 (R/W) Comparator Register 13 
.SS "__IOM uint32_t COMP14"
Offset: 0x100 (R/W) Comparator Register 14 
.SS "__IOM uint32_t COMP15"
Offset: 0x110 (R/W) Comparator Register 15 
.SS "__IOM uint32_t COMP2"
Offset: 0x040 (R/W) Comparator Register 2 
.SS "__IOM uint32_t COMP3"
Offset: 0x050 (R/W) Comparator Register 3 
.SS "__IOM uint32_t COMP4"
Offset: 0x060 (R/W) Comparator Register 4 
.SS "__IOM uint32_t COMP5"
Offset: 0x070 (R/W) Comparator Register 5 
.SS "__IOM uint32_t COMP6"
Offset: 0x080 (R/W) Comparator Register 6 
.SS "__IOM uint32_t COMP7"
Offset: 0x090 (R/W) Comparator Register 7 
.SS "__IOM uint32_t COMP8"
Offset: 0x0A0 (R/W) Comparator Register 8 
.SS "__IOM uint32_t COMP9"
Offset: 0x0B0 (R/W) Comparator Register 9 
.SS "__IM uint32_t CPUID"
Offset: 0x000 (R/ ) CPUID Base Register 
.SS "__IOM uint32_t CSPSR"
Offset: 0x004 (R/W) Current Parallel Port Sizes Register
.PP
Offset: 0x004 (R/W) Current Parallel Port Size Register 
.SS "__IOM uint32_t CTRL"
Offset: 0x000 (R/W) SysTick Control and Status Register 
.SS "__IOM uint32_t CTRL"
Offset: 0x000 (R/W) Control Register 
.SS "__IOM uint32_t DAUTHCTRL"
Offset: 0x014 (R/W) Debug Authentication Control Register 
.SS "__IOM uint32_t DCRDR"
Offset: 0x008 (R/W) Debug Core Register Data Register 
.SS "__OM uint32_t DCRSR"
Offset: 0x004 ( /W) Debug Core Register Selector Register 
.SS "__IOM uint32_t DEMCR"
Offset: 0x00C (R/W) Debug Exception and Monitor Control Register 
.SS "__IM uint32_t DEVID"
Offset: 0xFC8 (R/ ) Device Configuration Register
.PP
Offset: 0xFC8 (R/ ) TPIU_DEVID 
.SS "__IM uint32_t DEVTYPE"
Offset: 0xFCC (R/ ) Device Type Register
.PP
Offset: 0xFCC (R/ ) Device Type Identifier Register
.PP
Offset: 0xFCC (R/ ) TPIU_DEVTYPE 
.SS "__IOM uint32_t DHCSR"
Offset: 0x000 (R/W) Debug Halting Control and Status Register 
.SS "__IOM uint32_t DSCSR"
Offset: 0x018 (R/W) Debug Security Control and Status Register 
.SS "__IOM uint32_t FFCR"
Offset: 0x304 (R/W) Formatter and Flush Control Register 
.SS "__IM uint32_t FFSR"
Offset: 0x300 (R/ ) Formatter and Flush Status Register 
.SS "__IOM uint32_t FUNCTION0"
Offset: 0x028 (R/W) Function Register 0 
.SS "__IOM uint32_t FUNCTION1"
Offset: 0x038 (R/W) Function Register 1 
.SS "__IOM uint32_t FUNCTION10"
Offset: 0x0C8 (R/W) Function Register 10 
.SS "__IOM uint32_t FUNCTION11"
Offset: 0x0D8 (R/W) Function Register 11 
.SS "__IOM uint32_t FUNCTION12"
Offset: 0x0E8 (R/W) Function Register 12 
.SS "__IOM uint32_t FUNCTION13"
Offset: 0x0F8 (R/W) Function Register 13 
.SS "__IOM uint32_t FUNCTION14"
Offset: 0x108 (R/W) Function Register 14 
.SS "__IOM uint32_t FUNCTION15"
Offset: 0x118 (R/W) Function Register 15 
.SS "__IOM uint32_t FUNCTION2"
Offset: 0x048 (R/W) Function Register 2 
.SS "__IOM uint32_t FUNCTION3"
Offset: 0x058 (R/W) Function Register 3 
.SS "__IOM uint32_t FUNCTION4"
Offset: 0x068 (R/W) Function Register 4 
.SS "__IOM uint32_t FUNCTION5"
Offset: 0x078 (R/W) Function Register 5 
.SS "__IOM uint32_t FUNCTION6"
Offset: 0x088 (R/W) Function Register 6 
.SS "__IOM uint32_t FUNCTION7"
Offset: 0x098 (R/W) Function Register 7 
.SS "__IOM uint32_t FUNCTION8"
Offset: 0x0A8 (R/W) Function Register 8 
.SS "__IOM uint32_t FUNCTION9"
Offset: 0x0B8 (R/W) Function Register 9 
.SS "__IOM uint32_t IABR"
Offset: 0x200 (R/W) Interrupt Active bit Register 
.SS "__IOM uint32_t ICER"
Offset: 0x080 (R/W) Interrupt Clear Enable Register 
.SS "__IOM uint32_t ICPR"
Offset: 0x180 (R/W) Interrupt Clear Pending Register 
.SS "__IOM uint32_t ICSR"
Offset: 0x004 (R/W) Interrupt Control and State Register 
.SS "__IOM uint8_t IP"
Offset: 0x300 (R/W) Interrupt Priority Register
.PP
Offset: 0x300 (R/W) Interrupt Priority Register (8Bit wide) 
.SS "__IOM uint8_t IPR"
Offset: 0x300 (R/W) Interrupt Priority Register
.PP
Offset: 0x300 (R/W) Interrupt Priority Register (8Bit wide) 
.SS "__IOM uint32_t ISER"
Offset: 0x000 (R/W) Interrupt Set Enable Register 
.SS "__IOM uint32_t ISPR"
Offset: 0x100 (R/W) Interrupt Set Pending Register 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "__IM uint32_t ITATBCTR0"
Offset: 0xEF8 (R/ ) Integration Test ATB Control Register 0
.PP
Offset: 0xEF8 (R/ ) ITATBCTR0 
.SS "__IM uint32_t ITATBCTR2"
Offset: 0xEF0 (R/W) Integration Test ATB Control Register 2
.PP
Offset: 0xEF0 (R/ ) ITATBCTR2 
.SS "__IOM uint32_t ITCTRL"
Offset: 0xF00 (R/W) Integration Mode Control 
.SS "__IM uint32_t ITFTTD0"
Offset: 0xEEC (R/ ) Integration Test FIFO Test Data 0 Register 
.SS "__IM uint32_t ITFTTD1"
Offset: 0xEFC (R/ ) Integration Test FIFO Test Data 1 Register 
.SS "__IOM uint32_t ITNS"
Offset: 0x280 (R/W) Interrupt Non-Secure State Register 
.SS "__OM uint32_t LAR"
Offset: 0xFB0 ( /W) Software Lock Access Register 
.SS "__IOM uint32_t LOAD"
Offset: 0x004 (R/W) SysTick Reload Value Register 
.SS "__IM uint32_t LSR"
Offset: 0xFB4 (R/ ) Software Lock Status Register 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t nPRIV"
bit: 0 Execution privilege in Thread mode 
.SS "uint32_t nPRIV"
bit: 0 Execution privilege in Thread mode 
.SS "uint32_t nPRIV"
bit: 0 Execution privilege in Thread mode 
.SS "uint32_t nPRIV"
bit: 0 Execution privilege in Thread mode 
.SS "__IM uint32_t PCSR"
Offset: 0x01C (R/ ) Program Counter Sample Register 
.SS "__IOM uint32_t PSCR"
Offset: 0x308 (R/W) Periodic Synchronization Control Register 
.SS "__IOM uint32_t SCR"
Offset: 0x010 (R/W) System Control Register 
.SS "__IOM uint32_t SFCR"
Offset: 0x290 (R/W) Security Features Control Register 
.SS "__IOM uint32_t SHCSR"
Offset: 0x024 (R/W) System Handler Control and State Register 
.SS "__IOM uint8_t SHP"
Offset: 0x01C (R/W) System Handlers Priority Registers\&. [0] is RESERVED
.PP
Offset: 0x018 (R/W) System Handlers Priority Registers (4-7, 8-11, 12-15) 
.SS "__IOM uint8_t SHPR"
Offset: 0x01C (R/W) System Handlers Priority Registers\&. [0] is RESERVED
.PP
Offset: 0x018 (R/W) System Handlers Priority Registers (4-7, 8-11, 12-15) 
.SS "__IOM uint32_t SPPR"
Offset: 0x0F0 (R/W) Selected Pin Protocol Register 
.SS "uint32_t SPSEL"
bit: 1 Stack-pointer select 
.SS "uint32_t SPSEL"
bit: 1 Stack-pointer select
.PP
bit: 1 Stack to be used 
.SS "uint32_t SPSEL"
bit: 1 Stack to be used 
.SS "uint32_t SPSEL"
bit: 1 Stack to be used 
.SS "uint32_t SPSEL"
bit: 1 Stack to be used 
.SS "uint32_t SPSEL"
bit: 1 Stack-pointer select 
.SS "uint32_t SPSEL"
bit: 1 Stack to be used 
.SS "__IM uint32_t SSPSR"
Offset: 0x000 (R/ ) Supported Parallel Port Sizes Register
.PP
Offset: 0x000 (R/ ) Supported Parallel Port Size Register 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0)
.PP
bit: 24 Thumb bit 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0) 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0) 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0) 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0) 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0) 
.SS "uint32_t T"
bit: 24 Thumb bit (read 0) 
.SS "__IM uint32_t TRIGGER"
Offset: 0xEE8 (R/ ) TRIGGER Register 
.SS "__IM uint32_t TYPE"
Offset: 0xFC8 (R/ ) Device Identifier Register 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "__IOM uint32_t VAL"
Offset: 0x008 (R/W) SysTick Current Value Register 
.SS "uint32_t w"
Type used for word access 
.SS "uint32_t w"
Type used for word access 
.SS "uint32_t w"
Type used for word access 
.SS "uint32_t w"
Type used for word access 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
