.TH "EXTI_Exported_Types" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Exported_Types \- EXTI Exported Types
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEXTI_HandleTypeDef\fP"
.br
.RI "EXTI Handle structure definition\&. "
.ti -1c
.RI "struct \fBEXTI_ConfigTypeDef\fP"
.br
.RI "EXTI Configuration structure definition\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEXTI_CallbackIDTypeDef\fP { \fBHAL_EXTI_COMMON_CB_ID\fP = 0x00U }"
.br
.RI "HAL EXTI common Callback ID enumeration definition\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
