.TH "EXTI_GPIOSel" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_GPIOSel \- EXTI GPIOSel
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXTI_GPIOA\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBEXTI_GPIOB\fP   0x00000001u"
.br
.ti -1c
.RI "#define \fBEXTI_GPIOC\fP   0x00000002u"
.br
.ti -1c
.RI "#define \fBEXTI_GPIOD\fP   0x00000003u"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
