.TH "FLASHEx_OB_Data_Address" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_OB_Data_Address \- Option Byte Data Address
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_DATA_ADDRESS_DATA0\fP   0x1FFFF804U"
.br
.ti -1c
.RI "#define \fBOB_DATA_ADDRESS_DATA1\fP   0x1FFFF806U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
