.TH "FLASHEx_Exported_Functions_Group2" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Exported_Functions_Group2 \- FLASHEx_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_OBErase\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_OBProgram\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_OBGetConfig\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.ti -1c
.RI "uint32_t \fBHAL_FLASHEx_OBGetUserData\fP (uint32_t DATAAdress)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
