.TH "FLASHEx_Private_Constants" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Private_Constants \- FLASHEx_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_SIZE_DATA_REGISTER\fP   0x1FFFF7E0U"
.br
.ti -1c
.RI "#define \fBOBR_REG_INDEX\fP   1U"
.br
.ti -1c
.RI "#define \fBSR_FLAG_MASK\fP   ((uint32_t)(\fBFLASH_SR_BSY\fP | \fBFLASH_SR_PGERR\fP | \fBFLASH_SR_WRPRTERR\fP | \fBFLASH_SR_EOP\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
