.TH "GPIO_Exported_Functions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Functions \- GPIO_Exported_Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGPIO_Exported_Functions_Group1\fP"
.br
.ti -1c
.RI "\fBGPIO_Exported_Functions_Group2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
