.TH "GPIOEx_EVENTOUT" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOEx_EVENTOUT \- EVENTOUT Cortex Configuration
.PP
 \- This section propose definition to use the Cortex EVENTOUT signal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBEVENTOUT Pin\fP"
.br
.ti -1c
.RI "\fBEVENTOUT Port\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This section propose definition to use the Cortex EVENTOUT signal\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
