.TH "HAL_Aliased_Functions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Aliased_Functions \- HAL Generic Aliased Functions maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_EnableDBGSleepMode\fP   HAL_DBGMCU_EnableDBGSleepMode"
.br
.ti -1c
.RI "#define \fBHAL_DisableDBGSleepMode\fP   HAL_DBGMCU_DisableDBGSleepMode"
.br
.ti -1c
.RI "#define \fBHAL_EnableDBGStopMode\fP   HAL_DBGMCU_EnableDBGStopMode"
.br
.ti -1c
.RI "#define \fBHAL_DisableDBGStopMode\fP   HAL_DBGMCU_DisableDBGStopMode"
.br
.ti -1c
.RI "#define \fBHAL_EnableDBGStandbyMode\fP   HAL_DBGMCU_EnableDBGStandbyMode"
.br
.ti -1c
.RI "#define \fBHAL_DisableDBGStandbyMode\fP   HAL_DBGMCU_DisableDBGStandbyMode"
.br
.ti -1c
.RI "#define \fBHAL_DBG_LowPowerConfig\fP(Periph,  cmd)   (((cmd)==ENABLE)? HAL_DBGMCU_DBG_EnableLowPowerConfig(Periph) : HAL_DBGMCU_DBG_DisableLowPowerConfig(Periph))"
.br
.ti -1c
.RI "#define \fBHAL_VREFINT_OutputSelect\fP   HAL_SYSCFG_VREFINT_OutputSelect"
.br
.ti -1c
.RI "#define \fBHAL_Lock_Cmd\fP(cmd)   (((cmd)==ENABLE) ? HAL_SYSCFG_Enable_Lock_VREFINT() : HAL_SYSCFG_Disable_Lock_VREFINT())"
.br
.ti -1c
.RI "#define \fBHAL_VREFINT_Cmd\fP(cmd)   (((cmd)==ENABLE)? HAL_SYSCFG_EnableVREFINT() : HAL_SYSCFG_DisableVREFINT())"
.br
.ti -1c
.RI "#define \fBHAL_ADC_EnableBuffer_Cmd\fP(cmd)   (((cmd)==ENABLE) ? HAL_ADCEx_EnableVREFINT() : HAL_ADCEx_DisableVREFINT())"
.br
.ti -1c
.RI "#define \fBHAL_ADC_EnableBufferSensor_Cmd\fP(cmd)   (((cmd)==ENABLE) ?  HAL_ADCEx_EnableVREFINTTempSensor() : HAL_ADCEx_DisableVREFINTTempSensor())"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
