.TH "HAL_PCCARD_Aliased_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_PCCARD_Aliased_Defines \- HAL PCCARD Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCF_DATA\fP   ATA_DATA"
.br
.ti -1c
.RI "#define \fBCF_SECTOR_COUNT\fP   ATA_SECTOR_COUNT"
.br
.ti -1c
.RI "#define \fBCF_SECTOR_NUMBER\fP   ATA_SECTOR_NUMBER"
.br
.ti -1c
.RI "#define \fBCF_CYLINDER_LOW\fP   ATA_CYLINDER_LOW"
.br
.ti -1c
.RI "#define \fBCF_CYLINDER_HIGH\fP   ATA_CYLINDER_HIGH"
.br
.ti -1c
.RI "#define \fBCF_CARD_HEAD\fP   ATA_CARD_HEAD"
.br
.ti -1c
.RI "#define \fBCF_STATUS_CMD\fP   ATA_STATUS_CMD"
.br
.ti -1c
.RI "#define \fBCF_STATUS_CMD_ALTERNATE\fP   ATA_STATUS_CMD_ALTERNATE"
.br
.ti -1c
.RI "#define \fBCF_COMMON_DATA_AREA\fP   ATA_COMMON_DATA_AREA"
.br
.ti -1c
.RI "#define \fBCF_READ_SECTOR_CMD\fP   ATA_READ_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_WRITE_SECTOR_CMD\fP   ATA_WRITE_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_ERASE_SECTOR_CMD\fP   ATA_ERASE_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_IDENTIFY_CMD\fP   ATA_IDENTIFY_CMD"
.br
.ti -1c
.RI "#define \fBPCCARD_StatusTypedef\fP   HAL_PCCARD_StatusTypeDef"
.br
.ti -1c
.RI "#define \fBPCCARD_SUCCESS\fP   HAL_PCCARD_STATUS_SUCCESS"
.br
.ti -1c
.RI "#define \fBPCCARD_ONGOING\fP   HAL_PCCARD_STATUS_ONGOING"
.br
.ti -1c
.RI "#define \fBPCCARD_ERROR\fP   HAL_PCCARD_STATUS_ERROR"
.br
.ti -1c
.RI "#define \fBPCCARD_TIMEOUT\fP   HAL_PCCARD_STATUS_TIMEOUT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
