.TH "HAL_IRDA_Aliased_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_IRDA_Aliased_Macros \- HAL IRDA Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__IRDA_DISABLE\fP   __HAL_IRDA_DISABLE"
.br
.ti -1c
.RI "#define \fB__IRDA_ENABLE\fP   __HAL_IRDA_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_IRDA_GETCLOCKSOURCE\fP   IRDA_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__HAL_IRDA_MASK_COMPUTATION\fP   IRDA_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fB__IRDA_GETCLOCKSOURCE\fP   IRDA_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__IRDA_MASK_COMPUTATION\fP   IRDA_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fBIS_IRDA_ONEBIT_SAMPLE\fP   IS_IRDA_ONE_BIT_SAMPLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
