.TH "HAL_TIM_Aliased_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TIM_Aliased_Defines \- HAL TIM Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCCER_CCxE_MASK\fP   TIM_CCER_CCxE_MASK"
.br
.ti -1c
.RI "#define \fBCCER_CCxNE_MASK\fP   TIM_CCER_CCxNE_MASK"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CR1\fP   TIM_DMABASE_CR1"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CR2\fP   TIM_DMABASE_CR2"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_SMCR\fP   TIM_DMABASE_SMCR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DIER\fP   TIM_DMABASE_DIER"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_SR\fP   TIM_DMABASE_SR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_EGR\fP   TIM_DMABASE_EGR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR1\fP   TIM_DMABASE_CCMR1"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR2\fP   TIM_DMABASE_CCMR2"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCER\fP   TIM_DMABASE_CCER"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CNT\fP   TIM_DMABASE_CNT"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_PSC\fP   TIM_DMABASE_PSC"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_ARR\fP   TIM_DMABASE_ARR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_RCR\fP   TIM_DMABASE_RCR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR1\fP   TIM_DMABASE_CCR1"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR2\fP   TIM_DMABASE_CCR2"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR3\fP   TIM_DMABASE_CCR3"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR4\fP   TIM_DMABASE_CCR4"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_BDTR\fP   TIM_DMABASE_BDTR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DCR\fP   TIM_DMABASE_DCR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DMAR\fP   TIM_DMABASE_DMAR"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR1\fP   TIM_DMABASE_OR1"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR3\fP   TIM_DMABASE_CCMR3"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR5\fP   TIM_DMABASE_CCR5"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR6\fP   TIM_DMABASE_CCR6"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR2\fP   TIM_DMABASE_OR2"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR3\fP   TIM_DMABASE_OR3"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR\fP   TIM_DMABASE_OR"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Update\fP   \fBTIM_EVENTSOURCE_UPDATE\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC1\fP   \fBTIM_EVENTSOURCE_CC1\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC2\fP   \fBTIM_EVENTSOURCE_CC2\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC3\fP   \fBTIM_EVENTSOURCE_CC3\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC4\fP   \fBTIM_EVENTSOURCE_CC4\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_COM\fP   \fBTIM_EVENTSOURCE_COM\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Trigger\fP   \fBTIM_EVENTSOURCE_TRIGGER\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Break\fP   \fBTIM_EVENTSOURCE_BREAK\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Break2\fP   TIM_EVENTSOURCE_BREAK2"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_1Transfer\fP   \fBTIM_DMABURSTLENGTH_1TRANSFER\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_2Transfers\fP   \fBTIM_DMABURSTLENGTH_2TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_3Transfers\fP   \fBTIM_DMABURSTLENGTH_3TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_4Transfers\fP   \fBTIM_DMABURSTLENGTH_4TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_5Transfers\fP   \fBTIM_DMABURSTLENGTH_5TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_6Transfers\fP   \fBTIM_DMABURSTLENGTH_6TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_7Transfers\fP   \fBTIM_DMABURSTLENGTH_7TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_8Transfers\fP   \fBTIM_DMABURSTLENGTH_8TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_9Transfers\fP   \fBTIM_DMABURSTLENGTH_9TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_10Transfers\fP   \fBTIM_DMABURSTLENGTH_10TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_11Transfers\fP   \fBTIM_DMABURSTLENGTH_11TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_12Transfers\fP   \fBTIM_DMABURSTLENGTH_12TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_13Transfers\fP   \fBTIM_DMABURSTLENGTH_13TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_14Transfers\fP   \fBTIM_DMABURSTLENGTH_14TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_15Transfers\fP   \fBTIM_DMABURSTLENGTH_15TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_16Transfers\fP   \fBTIM_DMABURSTLENGTH_16TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_17Transfers\fP   \fBTIM_DMABURSTLENGTH_17TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_18Transfers\fP   \fBTIM_DMABURSTLENGTH_18TRANSFERS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
