.TH "HAL_Exported_Functions_Group2" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Functions_Group2 \- HAL_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_IncTick\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_Delay\fP (uint32_t Delay)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetTick\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetTickPrio\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SetTickFreq\fP (HAL_TickFreqTypeDef Freq)"
.br
.ti -1c
.RI "HAL_TickFreqTypeDef \fBHAL_GetTickFreq\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SuspendTick\fP (void)"
.br
.RI "Suspend Tick increment\&. "
.ti -1c
.RI "void \fBHAL_ResumeTick\fP (void)"
.br
.RI "Resume Tick increment\&. "
.ti -1c
.RI "uint32_t \fBHAL_GetHalVersion\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetREVID\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetDEVID\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetUIDw0\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetUIDw1\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetUIDw2\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGSleepMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGSleepMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGStopMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGStopMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGStandbyMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGStandbyMode\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_ResumeTick (void)"

.PP
Resume Tick increment\&. 
.PP
\fBNote\fP
.RS 4
Enable the tick increment by Enabling TIM4 update interrupt\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "void HAL_SuspendTick (void)"

.PP
Suspend Tick increment\&. 
.PP
\fBNote\fP
.RS 4
Disable the tick increment by disabling TIM4 update interrupt\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
