.TH "HAL_Aliased_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Aliased_Macros \- HAL Generic Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_GET_BOOT_MODE\fP   __HAL_SYSCFG_GET_BOOT_MODE"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_FLASH\fP   __HAL_SYSCFG_REMAPMEMORY_FLASH"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_SYSTEMFLASH\fP   __HAL_SYSCFG_REMAPMEMORY_SYSTEMFLASH"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_SRAM\fP   __HAL_SYSCFG_REMAPMEMORY_SRAM"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_FMC\fP   __HAL_SYSCFG_REMAPMEMORY_FMC"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_FMC_SDRAM\fP   __HAL_SYSCFG_REMAPMEMORY_FMC_SDRAM"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_FSMC\fP   __HAL_SYSCFG_REMAPMEMORY_FSMC"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPMEMORY_QUADSPI\fP   __HAL_SYSCFG_REMAPMEMORY_QUADSPI"
.br
.ti -1c
.RI "#define \fB__HAL_FMC_BANK\fP   __HAL_SYSCFG_FMC_BANK"
.br
.ti -1c
.RI "#define \fB__HAL_GET_FLAG\fP   __HAL_SYSCFG_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_CLEAR_FLAG\fP   __HAL_SYSCFG_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_VREFINT_OUT_ENABLE\fP   __HAL_SYSCFG_VREFINT_OUT_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_VREFINT_OUT_DISABLE\fP   __HAL_SYSCFG_VREFINT_OUT_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_SYSCFG_SRAM2_WRP_ENABLE\fP   __HAL_SYSCFG_SRAM2_WRP_0_31_ENABLE"
.br
.ti -1c
.RI "#define \fBSYSCFG_FLAG_VREF_READY\fP   SYSCFG_FLAG_VREFINT_READY"
.br
.ti -1c
.RI "#define \fBSYSCFG_FLAG_RC48\fP   RCC_FLAG_HSI48"
.br
.ti -1c
.RI "#define \fBIS_SYSCFG_FASTMODEPLUS_CONFIG\fP   IS_I2C_FASTMODEPLUS"
.br
.ti -1c
.RI "#define \fBUFB_MODE_BitNumber\fP   UFB_MODE_BIT_NUMBER"
.br
.ti -1c
.RI "#define \fBCMP_PD_BitNumber\fP   CMP_PD_BIT_NUMBER"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
