.TH "HAL_AES_Aliased_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_AES_Aliased_Macros \- HAL CRYP Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAES_IT_CC\fP   CRYP_IT_CC"
.br
.ti -1c
.RI "#define \fBAES_IT_ERR\fP   CRYP_IT_ERR"
.br
.ti -1c
.RI "#define \fBAES_FLAG_CCF\fP   CRYP_FLAG_CCF"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
