.TH "HAL_FLASH_Aliased_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_FLASH_Aliased_Defines \- HAL FLASH Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTYPEPROGRAM_BYTE\fP   FLASH_TYPEPROGRAM_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_HALFWORD\fP   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_WORD\fP   \fBFLASH_TYPEPROGRAM_WORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_DOUBLEWORD\fP   \fBFLASH_TYPEPROGRAM_DOUBLEWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_SECTORS\fP   FLASH_TYPEERASE_SECTORS"
.br
.ti -1c
.RI "#define \fBTYPEERASE_PAGES\fP   \fBFLASH_TYPEERASE_PAGES\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_PAGEERASE\fP   \fBFLASH_TYPEERASE_PAGES\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_MASSERASE\fP   \fBFLASH_TYPEERASE_MASSERASE\fP"
.br
.ti -1c
.RI "#define \fBWRPSTATE_DISABLE\fP   \fBOB_WRPSTATE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBWRPSTATE_ENABLE\fP   \fBOB_WRPSTATE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_TIMEOUT_VALUE\fP   FLASH_TIMEOUT_VALUE"
.br
.ti -1c
.RI "#define \fBOBEX_PCROP\fP   OPTIONBYTE_PCROP"
.br
.ti -1c
.RI "#define \fBOBEX_BOOTCONFIG\fP   OPTIONBYTE_BOOTCONFIG"
.br
.ti -1c
.RI "#define \fBPCROPSTATE_DISABLE\fP   OB_PCROP_STATE_DISABLE"
.br
.ti -1c
.RI "#define \fBPCROPSTATE_ENABLE\fP   OB_PCROP_STATE_ENABLE"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_BYTE\fP   FLASH_TYPEERASEDATA_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_HALFWORD\fP   FLASH_TYPEERASEDATA_HALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_WORD\fP   FLASH_TYPEERASEDATA_WORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_BYTE\fP   FLASH_TYPEPROGRAMDATA_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_HALFWORD\fP   FLASH_TYPEPROGRAMDATA_HALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_WORD\fP   FLASH_TYPEPROGRAMDATA_WORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTBYTE\fP   FLASH_TYPEPROGRAMDATA_FASTBYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTHALFWORD\fP   FLASH_TYPEPROGRAMDATA_FASTHALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTWORD\fP   FLASH_TYPEPROGRAMDATA_FASTWORD"
.br
.ti -1c
.RI "#define \fBPAGESIZE\fP   FLASH_PAGE_SIZE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTBYTE\fP   FLASH_TYPEPROGRAM_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTHALFWORD\fP   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTWORD\fP   \fBFLASH_TYPEPROGRAM_WORD\fP"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_1\fP   FLASH_VOLTAGE_RANGE_1"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_2\fP   FLASH_VOLTAGE_RANGE_2"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_3\fP   FLASH_VOLTAGE_RANGE_3"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_4\fP   FLASH_VOLTAGE_RANGE_4"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FAST\fP   FLASH_TYPEPROGRAM_FAST"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FAST_AND_LAST\fP   FLASH_TYPEPROGRAM_FAST_AND_LAST"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK1_AREAA\fP   OB_WRPAREA_BANK1_AREAA"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK1_AREAB\fP   OB_WRPAREA_BANK1_AREAB"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK2_AREAA\fP   OB_WRPAREA_BANK2_AREAA"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK2_AREAB\fP   OB_WRPAREA_BANK2_AREAB"
.br
.ti -1c
.RI "#define \fBIWDG_STDBY_FREEZE\fP   OB_IWDG_STDBY_FREEZE"
.br
.ti -1c
.RI "#define \fBIWDG_STDBY_ACTIVE\fP   OB_IWDG_STDBY_RUN"
.br
.ti -1c
.RI "#define \fBIWDG_STOP_FREEZE\fP   OB_IWDG_STOP_FREEZE"
.br
.ti -1c
.RI "#define \fBIWDG_STOP_ACTIVE\fP   OB_IWDG_STOP_RUN"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_NONE\fP   \fBHAL_FLASH_ERROR_NONE\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_RD\fP   HAL_FLASH_ERROR_RD"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PG\fP   \fBHAL_FLASH_ERROR_PROG\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGP\fP   HAL_FLASH_ERROR_PGS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_WRP\fP   \fBHAL_FLASH_ERROR_WRP\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPTV\fP   \fBHAL_FLASH_ERROR_OPTV\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPTVUSR\fP   HAL_FLASH_ERROR_OPTVUSR"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PROG\fP   \fBHAL_FLASH_ERROR_PROG\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OP\fP   HAL_FLASH_ERROR_OPERATION"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGA\fP   HAL_FLASH_ERROR_PGA"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_SIZE\fP   HAL_FLASH_ERROR_SIZE"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_SIZ\fP   HAL_FLASH_ERROR_SIZE"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGS\fP   HAL_FLASH_ERROR_PGS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_MIS\fP   HAL_FLASH_ERROR_MIS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_FAST\fP   HAL_FLASH_ERROR_FAST"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_FWWERR\fP   HAL_FLASH_ERROR_FWWERR"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_NOTZERO\fP   HAL_FLASH_ERROR_NOTZERO"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPERATION\fP   HAL_FLASH_ERROR_OPERATION"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_ERS\fP   HAL_FLASH_ERROR_ERS"
.br
.ti -1c
.RI "#define \fBOB_WDG_SW\fP   \fBOB_IWDG_SW\fP"
.br
.ti -1c
.RI "#define \fBOB_WDG_HW\fP   \fBOB_IWDG_HW\fP"
.br
.ti -1c
.RI "#define \fBOB_SDADC12_VDD_MONITOR_SET\fP   OB_SDACD_VDD_MONITOR_SET"
.br
.ti -1c
.RI "#define \fBOB_SDADC12_VDD_MONITOR_RESET\fP   OB_SDACD_VDD_MONITOR_RESET"
.br
.ti -1c
.RI "#define \fBOB_RAM_PARITY_CHECK_SET\fP   OB_SRAM_PARITY_SET"
.br
.ti -1c
.RI "#define \fBOB_RAM_PARITY_CHECK_RESET\fP   OB_SRAM_PARITY_RESET"
.br
.ti -1c
.RI "#define \fBIS_OB_SDADC12_VDD_MONITOR\fP   IS_OB_SDACD_VDD_MONITOR"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL0\fP   OB_RDP_LEVEL_0"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL1\fP   OB_RDP_LEVEL_1"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL2\fP   OB_RDP_LEVEL_2"
.br
.ti -1c
.RI "#define \fBOB_BOOT_ENTRY_FORCED_NONE\fP   OB_BOOT_LOCK_DISABLE"
.br
.ti -1c
.RI "#define \fBOB_BOOT_ENTRY_FORCED_FLASH\fP   OB_BOOT_LOCK_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
