.TH "HAL_UART_Aliased_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_UART_Aliased_Macros \- HAL UART Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_UART_GETCLOCKSOURCE\fP   UART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__HAL_UART_MASK_COMPUTATION\fP   UART_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fB__UART_GETCLOCKSOURCE\fP   UART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__UART_MASK_COMPUTATION\fP   UART_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fBIS_UART_WAKEUPMETHODE\fP   IS_UART_WAKEUPMETHOD"
.br
.ti -1c
.RI "#define \fBIS_UART_ONEBIT_SAMPLE\fP   IS_UART_ONE_BIT_SAMPLE"
.br
.ti -1c
.RI "#define \fBIS_UART_ONEBIT_SAMPLING\fP   IS_UART_ONE_BIT_SAMPLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
