.TH "Inc/hd44780.h" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/hd44780.h \- Модуль \fBhd44780\&.h\fP (заголовочный файл)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHD44780_TIMEOUT_CONTROL_ENABLE\fP"
.br
.RI "Uncomment if necessary to enable BF LCD timeout control\&. "
.ti -1c
.RI "#define \fBHD44780_4BIT_BUS_REQURED\fP"
.br
.RI "Uncomment if a 4-bit data bus is required\&. "
.ti -1c
.RI "#define \fBHD44780_BUSY_TIMEOUT_FLAG\fP   0x01"
.br
.RI "BF flag timeout for HD44780\&. "
.ti -1c
.RI "#define \fBHD44780_ROW_SIZE\fP   20"
.br
.RI "Number of symbols per row\&. "
.ti -1c
.RI "#define \fBHD44780_ROW_NUM\fP   4"
.br
.RI "Number of rows\&. "
.ti -1c
.RI "#define \fBHD44780_SCREEN_SIZE\fP   \fBHD44780_ROW_SIZE\fP*\fBHD44780_ROW_NUM\fP"
.br
.ti -1c
.RI "#define \fBHD44780_LINE1_START\fP   0x00"
.br
.RI "The starting address of the first line of segments\&. "
.ti -1c
.RI "#define \fBHD44780_LINE2_START\fP   0x40"
.br
.RI "The starting address of the second line of segments\&. "
.ti -1c
.RI "#define \fBHD44780_ROW1_START\fP   \fBHD44780_LINE1_START\fP"
.br
.ti -1c
.RI "#define \fBHD44780_ROW2_START\fP   \fBHD44780_LINE2_START\fP"
.br
.ti -1c
.RI "#define \fBHD44780_ROW3_START\fP   HD44780_ROW1_START + \fBHD44780_ROW_SIZE\fP"
.br
.ti -1c
.RI "#define \fBHD44780_ROW4_START\fP   HD44780_ROW2_START + \fBHD44780_ROW_SIZE\fP"
.br
.ti -1c
.RI "#define \fBHD44780_RQDATA\fP()   do{HAL_GPIO_WritePin(HD44780_RS_GPIO_Port, HD44780_RS_Pin, GPIO_PIN_SET);}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_RQCMD\fP()   do{HAL_GPIO_WritePin(HD44780_RS_GPIO_Port, HD44780_RS_Pin, GPIO_PIN_RESET);}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_RQRD\fP()   do{HAL_GPIO_WritePin(HD44780_RW_GPIO_Port, HD44780_RW_Pin, GPIO_PIN_SET);}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_RQWR\fP()   do{HAL_GPIO_WritePin(HD44780_RW_GPIO_Port, HD44780_RW_Pin, GPIO_PIN_RESET);}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_STARTSTB\fP()   do{HAL_GPIO_WritePin(HD44780_EN_GPIO_Port, HD44780_EN_Pin, GPIO_PIN_SET);}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_ENDSTB\fP()   do{HAL_GPIO_WritePin(HD44780_EN_GPIO_Port, HD44780_EN_Pin, GPIO_PIN_RESET);}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_BACKLIGHT_ON\fP()   do{__asm__('NOP');}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_BACKLIGHT_OFF\fP()   do{__asm__('NOP');}while(0)"
.br
.ti -1c
.RI "#define \fBHD44780_CLEAR\fP()   HD44780_writeCommand(0x01)"
.br
.ti -1c
.RI "#define \fBHD44780_RESET\fP()   HD44780_writeCommand(0x02)"
.br
.ti -1c
.RI "#define \fBHD44780_AC_DEC_MODE\fP()   HD44780_writeCommand(0x04)"
.br
.ti -1c
.RI "#define \fBHD44780_AC_INC_MODE\fP()   HD44780_writeCommand(0x06)"
.br
.ti -1c
.RI "#define \fBHD44780_SHIFT_LEFT_MODE\fP()   HD44780_writeCommand(0x05)"
.br
.ti -1c
.RI "#define \fBHD44780_SHIFT_RIGHT_MODE\fP()   HD44780_writeCommand(0x07)"
.br
.ti -1c
.RI "#define \fBHD44780_DISPLAY_ON\fP()   HD44780_writeCommand(0x0C)"
.br
.ti -1c
.RI "#define \fBHD44780_DISPLAY_OFF\fP()   HD44780_writeCommand(0x08)"
.br
.ti -1c
.RI "#define \fBHD44780_CURSOR_ON\fP()   HD44780_writeCommand(0x0E)"
.br
.ti -1c
.RI "#define \fBHD44780_CURSOR_OFF\fP()   HD44780_writeCommand(0x08)"
.br
.ti -1c
.RI "#define \fBHD44780_BLANK_ON\fP()   HD44780_writeCommand(0x0D)"
.br
.ti -1c
.RI "#define \fBHD44780_BLANK_OFF\fP()   HD44780_writeCommand(0x08)"
.br
.ti -1c
.RI "#define \fBHD44780_SET_CURSOR_LEFT\fP()   HD44780_writeCommand(0x10)"
.br
.ti -1c
.RI "#define \fBHD44780_SET_CURSOR_RIGHT\fP()   HD44780_writeCommand(0x14)"
.br
.ti -1c
.RI "#define \fBHD44780_SET_DISPLAY_LEFT\fP()   HD44780_writeCommand(0x18)"
.br
.ti -1c
.RI "#define \fBHD44780_SET_DISPLAY_RIGHT\fP()   HD44780_writeCommand(0x1C)"
.br
.ti -1c
.RI "#define \fBHD44780_SET_CGR_ADDR\fP(a)   HD44780_writeCommand(0x40 | a)"
.br
.ti -1c
.RI "#define \fBHD44780_SET_DDR_ADDR\fP(a)   HD44780_writeCommand(0x80 | a)"
.br
.ti -1c
.RI "#define \fBHD44780_SETUP\fP(param)   HD44780_writeCommand(0x20 | param)"
.br
.ti -1c
.RI "#define \fBHD44780_BUS4\fP   0"
.br
.ti -1c
.RI "#define \fBHD44780_BUS8\fP   (1 << 4)"
.br
.ti -1c
.RI "#define \fBHD44780_1ROW\fP   0"
.br
.ti -1c
.RI "#define \fBHD44780_2ROW\fP   (1 << 3)"
.br
.ti -1c
.RI "#define \fBHD44780_5x8CHAR\fP   0"
.br
.ti -1c
.RI "#define \fBHD44780_5x10CHAR\fP   (1 << 2)"
.br
.ti -1c
.RI "#define \fBHD44780_PAGE0\fP   (0x08)"
.br
.ti -1c
.RI "#define \fBHD44780_PAGE1\fP   (0x0A)"
.br
.ti -1c
.RI "#define \fBHD44780_BUS_MODE\fP   HD44780_BUS4"
.br
.ti -1c
.RI "#define \fBHD44780_BUSY_FLAG\fP   (1 << 7)"
.br
.ti -1c
.RI "#define \fBHD44780_BUSY_TIMEOUT_us\fP   1600"
.br
.ti -1c
.RI "#define \fBHD44780_BUSY_TIMEOUT_STEP_us\fP   100"
.br
.ti -1c
.RI "#define \fBHD44780_BUSY_TIMEOUT\fP   (HD44780_BUSY_TIMEOUT_us / HD44780_BUSY_TIMEOUT_STEP_us)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHD44780_init\fP (void)"
.br
.RI "Initial LCD initialization based on HD44780 controller\&. initial GPIO for control LCD\&. "
.ti -1c
.RI "void \fBHD44780_setRS\fP (uint8_t state)"
.br
.RI "The RS line of the LCD is set to LOW / HIGH\&. "
.ti -1c
.RI "void \fBHD44780_setRW\fP (uint8_t state)"
.br
.RI "The RW line of the LCD is set to LOW / HIGH\&. "
.ti -1c
.RI "void \fBHD44780_setEN\fP (uint8_t state)"
.br
.RI "The EN line of the LCD is set to LOW / HIGH\&. "
.ti -1c
.RI "void \fBHD44780_writeByte\fP (uint8_t data, uint8_t state)"
.br
.RI "Write cycle for LCD\&. "
.ti -1c
.RI "void \fBHD44780_setDataLow\fP (uint8_t data)"
.br
.RI "Цикл чтения из ЖКИ\&. "
.ti -1c
.RI "void \fBHD44780_setDataHigh\fP (uint8_t data)"
.br
.ti -1c
.RI "void \fBHD44780_setDataBus\fP (uint8_t data)"
.br
.ti -1c
.RI "void \fBHD44780_writeCommand\fP (uint8_t data)"
.br
.ti -1c
.RI "void \fBHD44780_writeData\fP (uint8_t data)"
.br
.ti -1c
.RI "void \fBusDelay\fP (uint16_t us)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Модуль \fBhd44780\&.h\fP (заголовочный файл)\&. 

Модуль драйвера ЖК дисплеем HD44780\&. 
.PP
\fBAuthor\fP
.RS 4
Donskih Dmitry, Артур Маркарян 
.RE
.PP
\fBDate\fP
.RS 4
02\&.03\&.2019 
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 - 2021 Donskih Dmitriy\&. All rights reserved\&."
.PP
This software component is licensed by Donskih Dmitriy under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Function Documentation"
.PP 
.SS "void HD44780_init (void)"

.PP
Initial LCD initialization based on HD44780 controller\&. initial GPIO for control LCD\&. The controller manufacturer recommends the following initialization sequence:
.IP "1." 4
Maintain a pause of at least 15 ms between the establishment of the operating supply voltage (> 4\&.5 V) and the performance of any operations with the controller\&.
.IP "2." 4
The first operation is to execute the command that selects the bus width (it must be the 0x30 command regardless of which interface you are going to use in the future), and do not check the value of the BF flag before performing this operation\&.
.IP "3." 4
Hold a pause of at least 4\&.1 ms\&.
.IP "4." 4
Repeat the command to select the bus width, also without checking the state of the BF flag before\&.
.IP "5." 4
Hold a pause of at least 100 µs\&.
.IP "6." 4
Repeat the command to select the bus width, also without checking the state of the BF flag before\&. These operations are initializing, and are designed to bring the controller to the initial operating mode (i\&.e\&. to switch to the operating mode with an 8-bit data bus) following this normal order (without pauses, but checking the BF flag), the operating modes are initialized , including the command for setting the bus width\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\&.\fP 
.RE
.PP
\fBReturns\fP
.RS 4
none\&. 
.RE
.PP

.PP

.SS "void HD44780_setDataLow (uint8_t data)"

.PP
Цикл чтения из ЖКИ\&. Перед циклом должны быть произведены установки линий: HD44780_wire_RS(команда/данные) HD44780_wire_RW(запись/чение) = 1 
.PP
\fBNote\fP
.RS 4
ПРЕДУПРЕЖДЕНИЕ!!! Во избежание порчи данных в неиспользуемых линиях порта данных ЖКИ в 4-х битном режиме, желательно запрещать прерывания, код которых взаимодействует со свободными линиями порта, либо в прерывании запоминать состояние регистров порта, перед внесением изменений, и восстанавливать данные по завершению прерывания\&.
.RE
.PP
Waiting cycle for LCD readiness\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Returns 1 if the LCD is ready and there is no timeout, otherwise 0\&. 
.RE
.PP

.SS "void HD44780_setEN (uint8_t state)"

.PP
The EN line of the LCD is set to LOW / HIGH\&. Function of setting the level on the EN line for LCD\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP (0 - start of strobe, 1 - end of strobe)\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "void HD44780_setRS (uint8_t state)"

.PP
The RS line of the LCD is set to LOW / HIGH\&. Function of setting the level on the RS line for LCD\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP (0 - requred CMD, 1 - requred DATA) 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "void HD44780_setRW (uint8_t state)"

.PP
The RW line of the LCD is set to LOW / HIGH\&. Function of setting the level on the RW line for LCD\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP (0 - write mode, 1 - read mode)\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "void HD44780_writeByte (uint8_t data, uint8_t state)"

.PP
Write cycle for LCD\&. Write byte to the LCD data bus (command or data)\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP - byte to be written\&. 
.br
\fIstate\fP - 0 if command byte, 1 - if data\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
