.TH "os_mailQ_def" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
os_mailQ_def
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_os\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBqueue_sz\fP"
.br
.RI "number of elements in the queue "
.ti -1c
.RI "uint32_t \fBitem_sz\fP"
.br
.RI "size of an item "
.ti -1c
.RI "struct \fBos_mailQ_cb\fP ** \fBcb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition structure for mail queue\&. 
.PP
\fBNote\fP
.RS 4
CAN BE CHANGED: \fB\fBos_mailQ_def\fP\fP is implementation specific in every CMSIS-RTOS\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
