.TH "os_mutex_def" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
os_mutex_def
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_os\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBdummy\fP"
.br
.RI "dummy value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Mutex Definition structure contains setup information for a mutex\&. 
.PP
\fBNote\fP
.RS 4
CAN BE CHANGED: \fB\fBos_mutex_def\fP\fP is implementation specific in every CMSIS-RTOS\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
