.TH "os_timer_def" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
os_timer_def
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_os\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "os_ptimer \fBptimer\fP"
.br
.RI "start address of a timer function "
.in -1c
.SH "Detailed Description"
.PP 
Timer Definition structure contains timer parameters\&. 
.PP
\fBNote\fP
.RS 4
CAN BE CHANGED: \fB\fBos_timer_def\fP\fP is implementation specific in every CMSIS-RTOS\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
