.TH "osEvent" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_os\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "osStatus \fBstatus\fP"
.br
.RI "status code: event or error information "
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   uint32_t \fBv\fP"
.br
.RI "message as 32-bit value "
.ti -1c
.RI "   void * \fBp\fP"
.br
.RI "message or mail as void pointer "
.ti -1c
.RI "   int32_t \fBsignals\fP"
.br
.RI "signal flags "
.ti -1c
.RI "} \fBvalue\fP"
.br
.RI "event value "
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBosMailQId\fP \fBmail_id\fP"
.br
.RI "mail id obtained by \fBosMailCreate\fP "
.ti -1c
.RI "   osMessageQId \fBmessage_id\fP"
.br
.RI "message id obtained by \fBosMessageCreate\fP "
.ti -1c
.RI "} \fBdef\fP"
.br
.RI "event definition "
.in -1c
.SH "Detailed Description"
.PP 
Event structure contains detailed information about an event\&. 
.PP
\fBNote\fP
.RS 4
MUST REMAIN UNCHANGED: \fBos_event\fP shall be consistent in every CMSIS-RTOS\&. However the struct may be extended at the end\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
