.TH "Peripheral_declaration" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Peripheral_declaration \- Peripheral_declaration
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM2\fP   ((\fBTIM_TypeDef\fP *)TIM2_BASE)"
.br
.ti -1c
.RI "#define \fBTIM3\fP   ((\fBTIM_TypeDef\fP *)TIM3_BASE)"
.br
.ti -1c
.RI "#define \fBTIM4\fP   ((\fBTIM_TypeDef\fP *)TIM4_BASE)"
.br
.ti -1c
.RI "#define \fBRTC\fP   ((\fBRTC_TypeDef\fP *)RTC_BASE)"
.br
.ti -1c
.RI "#define \fBWWDG\fP   ((\fBWWDG_TypeDef\fP *)WWDG_BASE)"
.br
.ti -1c
.RI "#define \fBIWDG\fP   ((\fBIWDG_TypeDef\fP *)IWDG_BASE)"
.br
.ti -1c
.RI "#define \fBSPI2\fP   ((\fBSPI_TypeDef\fP *)SPI2_BASE)"
.br
.ti -1c
.RI "#define \fBUSART2\fP   ((\fBUSART_TypeDef\fP *)USART2_BASE)"
.br
.ti -1c
.RI "#define \fBUSART3\fP   ((\fBUSART_TypeDef\fP *)USART3_BASE)"
.br
.ti -1c
.RI "#define \fBI2C1\fP   ((\fBI2C_TypeDef\fP *)I2C1_BASE)"
.br
.ti -1c
.RI "#define \fBI2C2\fP   ((\fBI2C_TypeDef\fP *)I2C2_BASE)"
.br
.ti -1c
.RI "#define \fBUSB\fP   ((\fBUSB_TypeDef\fP *)\fBUSB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBCAN1\fP   ((\fBCAN_TypeDef\fP *)CAN1_BASE)"
.br
.ti -1c
.RI "#define \fBBKP\fP   ((\fBBKP_TypeDef\fP *)BKP_BASE)"
.br
.ti -1c
.RI "#define \fBPWR\fP   ((\fBPWR_TypeDef\fP *)PWR_BASE)"
.br
.ti -1c
.RI "#define \fBAFIO\fP   ((\fBAFIO_TypeDef\fP *)AFIO_BASE)"
.br
.ti -1c
.RI "#define \fBEXTI\fP   ((\fBEXTI_TypeDef\fP *)EXTI_BASE)"
.br
.ti -1c
.RI "#define \fBGPIOA\fP   ((\fBGPIO_TypeDef\fP *)GPIOA_BASE)"
.br
.ti -1c
.RI "#define \fBGPIOB\fP   ((\fBGPIO_TypeDef\fP *)GPIOB_BASE)"
.br
.ti -1c
.RI "#define \fBGPIOC\fP   ((\fBGPIO_TypeDef\fP *)GPIOC_BASE)"
.br
.ti -1c
.RI "#define \fBGPIOD\fP   ((\fBGPIO_TypeDef\fP *)GPIOD_BASE)"
.br
.ti -1c
.RI "#define \fBGPIOE\fP   ((\fBGPIO_TypeDef\fP *)GPIOE_BASE)"
.br
.ti -1c
.RI "#define \fBADC1\fP   ((\fBADC_TypeDef\fP *)ADC1_BASE)"
.br
.ti -1c
.RI "#define \fBADC2\fP   ((\fBADC_TypeDef\fP *)ADC2_BASE)"
.br
.ti -1c
.RI "#define \fBADC12_COMMON\fP   ((\fBADC_Common_TypeDef\fP *)ADC1_BASE)"
.br
.ti -1c
.RI "#define \fBTIM1\fP   ((\fBTIM_TypeDef\fP *)TIM1_BASE)"
.br
.ti -1c
.RI "#define \fBSPI1\fP   ((\fBSPI_TypeDef\fP *)SPI1_BASE)"
.br
.ti -1c
.RI "#define \fBUSART1\fP   ((\fBUSART_TypeDef\fP *)USART1_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1\fP   ((\fBDMA_TypeDef\fP *)DMA1_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel1\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel1_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel2\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel2_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel3\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel3_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel4\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel4_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel5\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel5_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel6\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel6_BASE)"
.br
.ti -1c
.RI "#define \fBDMA1_Channel7\fP   ((\fBDMA_Channel_TypeDef\fP *)DMA1_Channel7_BASE)"
.br
.ti -1c
.RI "#define \fBRCC\fP   ((\fBRCC_TypeDef\fP *)RCC_BASE)"
.br
.ti -1c
.RI "#define \fBCRC\fP   ((\fBCRC_TypeDef\fP *)CRC_BASE)"
.br
.ti -1c
.RI "#define \fBFLASH\fP   ((\fBFLASH_TypeDef\fP *)\fBFLASH_R_BASE\fP)"
.br
.ti -1c
.RI "#define \fBOB\fP   ((\fBOB_TypeDef\fP *)\fBOB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBDBGMCU\fP   ((\fBDBGMCU_TypeDef\fP *)\fBDBGMCU_BASE\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
