.TH "PWR_Exported_Functions_Group1" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Functions_Group1 \- Initialization and de-initialization functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_PWR_DeInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableBkUpAccess\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableBkUpAccess\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
