.TH "PWR_SLEEP_mode_entry" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_SLEEP_mode_entry \- PWR SLEEP mode entry
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_SLEEPENTRY_WFI\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBPWR_SLEEPENTRY_WFE\fP   ((uint8_t)0x02)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
