.TH "PWR_Exported_Functions_Group2" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Functions_Group2 \- Peripheral Control functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_PWR_ConfigPVD\fP (\fBPWR_PVDTypeDef\fP *sConfigPVD)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnablePVD\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisablePVD\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableWakeUpPin\fP (uint32_t WakeUpPinx)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableWakeUpPin\fP (uint32_t WakeUpPinx)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSTOPMode\fP (uint32_t Regulator, uint8_t STOPEntry)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSLEEPMode\fP (uint32_t Regulator, uint8_t SLEEPEntry)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSTANDBYMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableSleepOnExit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableSleepOnExit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableSEVOnPend\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableSEVOnPend\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_PVD_IRQHandler\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_PVDCallback\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
