.TH "QueueDefinition" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueDefinition
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t * \fBpcHead\fP"
.br
.ti -1c
.RI "int8_t * \fBpcTail\fP"
.br
.ti -1c
.RI "int8_t * \fBpcWriteTo\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int8_t * \fBpcReadFrom\fP"
.br
.ti -1c
.RI "   UBaseType_t \fBuxRecursiveCallCount\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "\fBList_t\fP \fBxTasksWaitingToSend\fP"
.br
.ti -1c
.RI "\fBList_t\fP \fBxTasksWaitingToReceive\fP"
.br
.ti -1c
.RI "volatile UBaseType_t \fBuxMessagesWaiting\fP"
.br
.ti -1c
.RI "UBaseType_t \fBuxLength\fP"
.br
.ti -1c
.RI "UBaseType_t \fBuxItemSize\fP"
.br
.ti -1c
.RI "volatile int8_t \fBcRxLock\fP"
.br
.ti -1c
.RI "volatile int8_t \fBcTxLock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
