.TH "RCC_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_TypeDef \- Reset and Clock Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2RSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1RSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAHBENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2ENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1ENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBDCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reset and Clock Control\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
