.TH "RCC_Private_Constants" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Private_Constants \- RCC_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBRCC Timeout\fP"
.br
.ti -1c
.RI "\fBRegister offsets\fP"
.br
.ti -1c
.RI "\fBBitAddress AliasRegion\fP"
.br
.RI "RCC registers bit address in the alias region\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_CR_BYTE2_ADDRESS\fP   ((uint32_t)(RCC_BASE + RCC_CR_OFFSET + 0x02U))"
.br
.ti -1c
.RI "#define \fBRCC_CIR_BYTE1_ADDRESS\fP   ((uint32_t)(RCC_BASE + RCC_CIR_OFFSET + 0x01U))"
.br
.ti -1c
.RI "#define \fBRCC_CIR_BYTE2_ADDRESS\fP   ((uint32_t)(RCC_BASE + RCC_CIR_OFFSET + 0x02U))"
.br
.ti -1c
.RI "#define \fBCR_REG_INDEX\fP   ((uint8_t)1)"
.br
.ti -1c
.RI "#define \fBBDCR_REG_INDEX\fP   ((uint8_t)2)"
.br
.ti -1c
.RI "#define \fBCSR_REG_INDEX\fP   ((uint8_t)3)"
.br
.ti -1c
.RI "#define \fBRCC_FLAG_MASK\fP   ((uint8_t)0x1F)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
