.TH "RCCEx_APB2_Force_Release_Reset" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_APB2_Force_Release_Reset \- APB2 Force Release Reset
.PP
 \- Force or release APB2 peripheral reset\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Force or release APB2 peripheral reset\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
