.TH "RTC_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_TypeDef \- Real-Time Clock\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPRLH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPRLL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDIVH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDIVL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNTH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBALRH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBALRL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Real-Time Clock\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
