.TH "STM32_USB_OTG_DEVICE_LIBRARY" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32_USB_OTG_DEVICE_LIBRARY \- STM32_USB_OTG_DEVICE_LIBRARY
.PP
 \- For Usb device\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_CDC_IF\fP"
.br
.RI "Usb VCP device module\&. "
.ti -1c
.RI "\fBUSBD_DESC\fP"
.br
.RI "Usb device descriptors module\&. "
.in -1c
.SH "Detailed Description"
.PP 
For Usb device\&. 

Usb device library\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
