.TH "Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c \- PCD HAL module driver\&. This file provides firmware functions to manage the following functionalities of the USB Peripheral Controller:  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br

.SH "Detailed Description"
.PP 
PCD HAL module driver\&. This file provides firmware functions to manage the following functionalities of the USB Peripheral Controller: 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team
.IP "\(bu" 2
Initialization and de-initialization functions
.IP "\(bu" 2
IO operation functions
.IP "\(bu" 2
Peripheral Control functions
.IP "\(bu" 2
Peripheral State functions
.PP
.RE
.PP
.PP
.nf
==============================================================================
                  ##### How to use this driver #####
==============================================================================
  [..]
    The PCD HAL driver can be used as follows:

   (#) Declare a PCD_HandleTypeDef handle structure, for example:
       PCD_HandleTypeDef  hpcd;

   (#) Fill parameters of Init structure in HCD handle

   (#) Call HAL_PCD_Init() API to initialize the PCD peripheral (Core, Device core, ...)

   (#) Initialize the PCD low level resources through the HAL_PCD_MspInit() API:
       (##) Enable the PCD/USB Low Level interface clock using
            (+++) __HAL_RCC_USB_CLK_ENABLE(); For USB Device only FS peripheral

       (##) Initialize the related GPIO clocks
       (##) Configure PCD pin-out
       (##) Configure PCD NVIC interrupt

   (#)Associate the Upper USB device stack to the HAL PCD Driver:
       (##) hpcd.pData = pdev;

   (#)Enable PCD transmission and reception:
       (##) HAL_PCD_Start();.fi
.PP
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
