.TH "STM32_USB_DEVICE_LIBRARY" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32_USB_DEVICE_LIBRARY \- STM32_USB_DEVICE_LIBRARY
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUsbd_cdc\fP"
.br
.RI "This file is the Header file for \fBusbd_cdc\&.c\fP\&. "
.ti -1c
.RI "\fBUSBD_CDC\fP"
.br
.RI "usbd core module "
.ti -1c
.RI "\fBUSBD_CORE\fP"
.br
.RI "This file is the Header file for \fBusbd_core\&.c\fP file\&. "
.ti -1c
.RI "\fBUSBD_REQ\fP"
.br
.RI "header file for the usbd_req\&.c file "
.ti -1c
.RI "\fBUSBD_IOREQ\fP"
.br
.RI "header file for the \fBusbd_ioreq\&.c\fP file "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
