.TH "Src/stm32f1xx_it.c" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/stm32f1xx_it.c \- Interrupt Service Routines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'stm32f1xx_it\&.h'\fP
.br
\fC#include 'FreeRTOS\&.h'\fP
.br
\fC#include 'task\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBNMI_Handler\fP (void)"
.br
.RI "This function handles Non maskable interrupt\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP (void)"
.br
.RI "This function handles Hard fault interrupt\&. "
.ti -1c
.RI "void \fBMemManage_Handler\fP (void)"
.br
.RI "This function handles Memory management fault\&. "
.ti -1c
.RI "void \fBBusFault_Handler\fP (void)"
.br
.RI "This function handles Prefetch fault, memory access fault\&. "
.ti -1c
.RI "void \fBUsageFault_Handler\fP (void)"
.br
.RI "This function handles Undefined instruction or illegal state\&. "
.ti -1c
.RI "void \fBDebugMon_Handler\fP (void)"
.br
.RI "This function handles Debug monitor\&. "
.ti -1c
.RI "void \fBUSB_LP_CAN1_RX0_IRQHandler\fP (void)"
.br
.RI "This function handles USB low priority or CAN RX0 interrupts\&. "
.ti -1c
.RI "void \fBTIM4_IRQHandler\fP (void)"
.br
.RI "This function handles TIM4 global interrupt\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "PCD_HandleTypeDef \fBhpcd_USB_FS\fP"
.br
.ti -1c
.RI "\fBTIM_HandleTypeDef\fP \fBhtim4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interrupt Service Routines\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
.SS "(C) Copyright (c) 2019 Donskih Dmitriy\&. All rights reserved\&."
.PP
This software component is licensed by Donskih Dmitriy under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
