.TH "t_RcvBuffer" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_RcvBuffer
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbuffer\fP [HD44780_SCREEN_SIZE]"
.br
.ti -1c
.RI "uint8_t \fBinbuff\fP [256]"
.br
.ti -1c
.RI "uint8_t \fBpos_x\fP"
.br
.ti -1c
.RI "uint8_t \fBpos_y\fP"
.br
.ti -1c
.RI "uint8_t \fBpsize\fP"
.br
.ti -1c
.RI "uint8_t * \fBpdata\fP"
.br
.ti -1c
.RI "uint16_t \fBb_pos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
