.TH "TaskHandle_t" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskHandle_t \- TaskHandle_t
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h
.PP
Type by which tasks are referenced\&. For example, a call to xTaskCreate returns (via a pointer parameter) an TaskHandle_t variable that can then be used as a parameter to vTaskDelete to delete the task\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
