.TH "taskENABLE_INTERRUPTS" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
taskENABLE_INTERRUPTS \- taskENABLE_INTERRUPTS
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h
.PP
Macro to enable microcontroller interrupts\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
