.TH "taskEXIT_CRITICAL" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
taskEXIT_CRITICAL \- taskEXIT_CRITICAL
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h
.PP
Macro to mark the end of a critical code region\&. Preemptive context switches cannot occur when in a critical region\&.
.PP
NOTE: This may alter the stack (depending on the portable implementation) so must be used with care! 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
