.TH "taskYIELD" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
taskYIELD \- taskYIELD
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h
.PP
Macro for forcing a context switch\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
