.TH "TIM_DMA_Base_address" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_DMA_Base_address \- TIM DMA Base Address
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMABASE_CR1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CR2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_SMCR\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_DIER\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_SR\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_EGR\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCMR1\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCMR2\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCER\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CNT\fP   0x00000009U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_PSC\fP   0x0000000AU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_ARR\fP   0x0000000BU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_RCR\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR1\fP   0x0000000DU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR2\fP   0x0000000EU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR3\fP   0x0000000FU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR4\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_BDTR\fP   0x00000011U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_DCR\fP   0x00000012U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_DMAR\fP   0x00000013U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
