.TH "TIM_Exported_Functions_Group9" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group9 \- TIM Callbacks functions
.PP
 \- TIM Callbacks functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.RI "Period elapsed callback in non blocking mode\&. "
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OC_DelayElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_PulseFinishedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_PulseFinishedHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_TriggerCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_TriggerHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_ErrorCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Callbacks functions\&. 


.SH "Function Documentation"
.PP 
.SS "void HAL_TIM_PeriodElapsedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.PP
Period elapsed callback in non blocking mode\&. 
.PP
\fBNote\fP
.RS 4
This function is called when TIM4 interrupt took place, inside HAL_TIM_IRQHandler()\&. It makes a direct call to HAL_IncTick() to increment a global variable 'uwTick' used as application time base\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIhtim\fP : TIM handle 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
