.TH "TIM_AutoReloadPreload" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_AutoReloadPreload \- TIM Auto-Reload Preload
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_AUTORELOAD_PRELOAD_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_AUTORELOAD_PRELOAD_ENABLE\fP   \fBTIM_CR1_ARPE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_AUTORELOAD_PRELOAD_DISABLE   0x00000000U"
TIMx_ARR register is not buffered 
.SS "#define TIM_AUTORELOAD_PRELOAD_ENABLE   \fBTIM_CR1_ARPE\fP"
TIMx_ARR register is buffered 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
