.TH "tskTaskControlBlock" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tskTaskControlBlock
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile StackType_t * \fBpxTopOfStack\fP"
.br
.ti -1c
.RI "\fBListItem_t\fP \fBxStateListItem\fP"
.br
.ti -1c
.RI "\fBListItem_t\fP \fBxEventListItem\fP"
.br
.ti -1c
.RI "UBaseType_t \fBuxPriority\fP"
.br
.ti -1c
.RI "StackType_t * \fBpxStack\fP"
.br
.ti -1c
.RI "char \fBpcTaskName\fP [configMAX_TASK_NAME_LEN]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
