.TH "Src/usb_device.c" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/usb_device.c \- : This file implements the USB Device  

.SH SYNOPSIS
.br
.PP
\fC#include 'usb_device\&.h'\fP
.br
\fC#include 'usbd_core\&.h'\fP
.br
\fC#include 'usbd_desc\&.h'\fP
.br
\fC#include 'usbd_cdc\&.h'\fP
.br
\fC#include 'usbd_cdc_if\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_USB_DEVICE_Init\fP (void)"
.br
.RI "MX USB Device library initialization function\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_HandleTypeDef\fP \fBhUsbDeviceFS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: This file implements the USB Device 


.PP
\fBVersion\fP
.RS 4
: v2\&.0_Cube
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 Donskih Dmitriy\&. All rights reserved\&."
.PP
This software component is licensed by Donskih Dmitriy under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
