.TH "USBD_DescriptorsTypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DescriptorsTypeDef
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t *(* \fBGetDeviceDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetLangIDStrDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetManufacturerStrDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetProductStrDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetSerialStrDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetConfigurationStrDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.ti -1c
.RI "uint8_t *(* \fBGetInterfaceStrDescriptor\fP )(USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
