.TH "USBD_DEF_Exported_TypesDefinitions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DEF_Exported_TypesDefinitions \- USBD_DEF_Exported_TypesDefinitions
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBusb_setup_req\fP"
.br
.ti -1c
.RI "struct \fB_Device_cb\fP"
.br
.ti -1c
.RI "struct \fBUSBD_DescriptorsTypeDef\fP"
.br
.ti -1c
.RI "struct \fBUSBD_EndpointTypeDef\fP"
.br
.ti -1c
.RI "struct \fB_USBD_HandleTypeDef\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBusb_setup_req\fP \fBUSBD_SetupReqTypedef\fP"
.br
.ti -1c
.RI "typedef struct \fB_Device_cb\fP \fBUSBD_ClassTypeDef\fP"
.br
.ti -1c
.RI "typedef struct \fB_USBD_HandleTypeDef\fP \fBUSBD_HandleTypeDef\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUSBD_SpeedTypeDef\fP { \fBUSBD_SPEED_HIGH\fP = 0U, \fBUSBD_SPEED_FULL\fP = 1U, \fBUSBD_SPEED_LOW\fP = 2U }"
.br
.ti -1c
.RI "enum \fBUSBD_StatusTypeDef\fP { \fBUSBD_OK\fP = 0U, \fBUSBD_BUSY\fP, \fBUSBD_FAIL\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
