.TH "USBD_REQ_Private_Functions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_REQ_Private_Functions \- USBD_REQ_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_StdDevReq\fP (\fBUSBD_HandleTypeDef\fP *pdev, \fBUSBD_SetupReqTypedef\fP *req)"
.br
.RI "USBD_StdDevReq Handle standard usb device requests\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_StdItfReq\fP (\fBUSBD_HandleTypeDef\fP *pdev, \fBUSBD_SetupReqTypedef\fP *req)"
.br
.RI "USBD_StdItfReq Handle standard usb interface requests\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_StdEPReq\fP (\fBUSBD_HandleTypeDef\fP *pdev, \fBUSBD_SetupReqTypedef\fP *req)"
.br
.RI "USBD_StdEPReq Handle standard usb endpoint requests\&. "
.ti -1c
.RI "void \fBUSBD_ParseSetupRequest\fP (\fBUSBD_SetupReqTypedef\fP *req, uint8_t *pdata)"
.br
.RI "USBD_ParseSetupRequest Copy buffer into setup structure\&. "
.ti -1c
.RI "void \fBUSBD_CtlError\fP (\fBUSBD_HandleTypeDef\fP *pdev, \fBUSBD_SetupReqTypedef\fP *req)"
.br
.RI "USBD_CtlError Handle USB low level Error\&. "
.ti -1c
.RI "void \fBUSBD_GetString\fP (uint8_t *desc, uint8_t *unicode, uint16_t *len)"
.br
.RI "USBD_GetString Convert Ascii string into unicode one\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void USBD_CtlError (\fBUSBD_HandleTypeDef\fP * pdev, \fBUSBD_SetupReqTypedef\fP * req)"

.PP
USBD_CtlError Handle USB low level Error\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIreq\fP usb request 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "void USBD_GetString (uint8_t * desc, uint8_t * unicode, uint16_t * len)"

.PP
USBD_GetString Convert Ascii string into unicode one\&. 
.PP
\fBParameters\fP
.RS 4
\fIdesc\fP : descriptor buffer 
.br
\fIunicode\fP : Formatted string buffer (unicode) 
.br
\fIlen\fP : descriptor length 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "void USBD_ParseSetupRequest (\fBUSBD_SetupReqTypedef\fP * req, uint8_t * pdata)"

.PP
USBD_ParseSetupRequest Copy buffer into setup structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIreq\fP usb request 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_StdDevReq (\fBUSBD_HandleTypeDef\fP * pdev, \fBUSBD_SetupReqTypedef\fP * req)"

.PP
USBD_StdDevReq Handle standard usb device requests\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIreq\fP usb request 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_StdEPReq (\fBUSBD_HandleTypeDef\fP * pdev, \fBUSBD_SetupReqTypedef\fP * req)"

.PP
USBD_StdEPReq Handle standard usb endpoint requests\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIreq\fP usb request 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_StdItfReq (\fBUSBD_HandleTypeDef\fP * pdev, \fBUSBD_SetupReqTypedef\fP * req)"

.PP
USBD_StdItfReq Handle standard usb interface requests\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIreq\fP usb request 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
