.TH "USBD_CDC_IF_Private_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC_IF_Private_Macros \- USBD_CDC_IF_Private_Macros
.PP
 \- Private macros\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Private macros\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
