.TH "USBD_CONF_Exported_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CONF_Exported_Defines \- USBD_CONF_Exported_Defines
.PP
 \- Defines for configuration of the Usb device\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBD_MAX_NUM_INTERFACES\fP   1"
.br
.ti -1c
.RI "#define \fBUSBD_MAX_NUM_CONFIGURATION\fP   1"
.br
.ti -1c
.RI "#define \fBUSBD_MAX_STR_DESC_SIZ\fP   512"
.br
.ti -1c
.RI "#define \fBUSBD_DEBUG_LEVEL\fP   3"
.br
.ti -1c
.RI "#define \fBUSBD_SELF_POWERED\fP   1"
.br
.ti -1c
.RI "#define \fBMAX_STATIC_ALLOC_SIZE\fP   512"
.br
.ti -1c
.RI "#define \fBDEVICE_FS\fP   0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines for configuration of the Usb device\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
