.TH "USBD_DEF_Exported_FunctionsPrototype" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DEF_Exported_FunctionsPrototype \- USBD_DEF_Exported_FunctionsPrototype
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
