.TH "USBD_IOREQ_Private_Functions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_IOREQ_Private_Functions \- USBD_IOREQ_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_CtlSendData\fP (\fBUSBD_HandleTypeDef\fP *pdev, uint8_t *pbuf, uint16_t len)"
.br
.RI "USBD_CtlSendData send data on the ctl pipe\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_CtlContinueSendData\fP (\fBUSBD_HandleTypeDef\fP *pdev, uint8_t *pbuf, uint16_t len)"
.br
.RI "USBD_CtlContinueSendData continue sending data on the ctl pipe\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_CtlPrepareRx\fP (\fBUSBD_HandleTypeDef\fP *pdev, uint8_t *pbuf, uint16_t len)"
.br
.RI "USBD_CtlPrepareRx receive data on the ctl pipe\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_CtlContinueRx\fP (\fBUSBD_HandleTypeDef\fP *pdev, uint8_t *pbuf, uint16_t len)"
.br
.RI "USBD_CtlContinueRx continue receive data on the ctl pipe\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_CtlSendStatus\fP (\fBUSBD_HandleTypeDef\fP *pdev)"
.br
.RI "USBD_CtlSendStatus send zero lzngth packet on the ctl pipe\&. "
.ti -1c
.RI "USBD_StatusTypeDef \fBUSBD_CtlReceiveStatus\fP (\fBUSBD_HandleTypeDef\fP *pdev)"
.br
.RI "USBD_CtlReceiveStatus receive zero lzngth packet on the ctl pipe\&. "
.ti -1c
.RI "uint32_t \fBUSBD_GetRxCount\fP (\fBUSBD_HandleTypeDef\fP *pdev, uint8_t ep_addr)"
.br
.RI "USBD_GetRxCount returns the received data length\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "USBD_StatusTypeDef USBD_CtlContinueRx (\fBUSBD_HandleTypeDef\fP * pdev, uint8_t * pbuf, uint16_t len)"

.PP
USBD_CtlContinueRx continue receive data on the ctl pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIbuff\fP pointer to data buffer 
.br
\fIlen\fP length of data to be received 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_CtlContinueSendData (\fBUSBD_HandleTypeDef\fP * pdev, uint8_t * pbuf, uint16_t len)"

.PP
USBD_CtlContinueSendData continue sending data on the ctl pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIbuff\fP pointer to data buffer 
.br
\fIlen\fP length of data to be sent 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_CtlPrepareRx (\fBUSBD_HandleTypeDef\fP * pdev, uint8_t * pbuf, uint16_t len)"

.PP
USBD_CtlPrepareRx receive data on the ctl pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIbuff\fP pointer to data buffer 
.br
\fIlen\fP length of data to be received 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_CtlReceiveStatus (\fBUSBD_HandleTypeDef\fP * pdev)"

.PP
USBD_CtlReceiveStatus receive zero lzngth packet on the ctl pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_CtlSendData (\fBUSBD_HandleTypeDef\fP * pdev, uint8_t * pbuf, uint16_t len)"

.PP
USBD_CtlSendData send data on the ctl pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIbuff\fP pointer to data buffer 
.br
\fIlen\fP length of data to be sent 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "USBD_StatusTypeDef USBD_CtlSendStatus (\fBUSBD_HandleTypeDef\fP * pdev)"

.PP
USBD_CtlSendStatus send zero lzngth packet on the ctl pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIstatus\fP 
.RE
.PP

.SS "uint32_t USBD_GetRxCount (\fBUSBD_HandleTypeDef\fP * pdev, uint8_t ep_addr)"

.PP
USBD_GetRxCount returns the received data length\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdev\fP device instance 
.br
\fIep_addr\fP endpoint address 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIRx\fP Data blength 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
