.TH "USBD_CDC_IF_Private_FunctionPrototypes" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC_IF_Private_FunctionPrototypes \- USBD_CDC_IF_Private_FunctionPrototypes
.PP
 \- Private functions declaration\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Private functions declaration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
