.TH "Inc/usbd_cdc_if.h" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/usbd_cdc_if.h \- : Header for \fBusbd_cdc_if\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'usbd_cdc\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBD_CDC_IF_WAIT\fP   0x00"
.br
.ti -1c
.RI "#define \fBUSBD_CDC_IF_DATAREADY\fP   0x01"
.br
.ti -1c
.RI "#define \fBUSBD_CDC_IF_ESC\fP   0x02"
.br
.ti -1c
.RI "#define \fBUSBD_CDC_IF_ERROR\fP   0xFF"
.br
.ti -1c
.RI "#define \fBVT100_ERASE_SCREEN\fP   '\\x1B[2J'"
.br
.RI "Erase Screen\&. "
.ti -1c
.RI "#define \fBVT100_YELLOW_ON\fP   '\\x1B[\\x21m'"
.br
.RI "Foreground Yellow\&. "
.ti -1c
.RI "#define \fBVT100_YELLOW_OFF\fP   '\\x1B[\\x2Bm'"
.br
.RI "Background Yellow\&. "
.ti -1c
.RI "#define \fBVT100_RED_ON\fP   '\\x1B[\\x1Fm'"
.br
.RI "Foreground Red\&. "
.ti -1c
.RI "#define \fBVT100_RED_OFF\fP   '\\x1B[\\x29m'"
.br
.RI "Background Red\&. "
.ti -1c
.RI "#define \fBVT100_BUZZER_ON\fP   '\\x1B[\\x32m'"
.br
.RI "Foreground Green\&. "
.ti -1c
.RI "#define \fBVT100_BUZZER_OFF\fP   '\\x1B[\\x42m'"
.br
.RI "Background Green\&. "
.ti -1c
.RI "#define \fBMESSAGE_YELLOW_ON\fP"
.br
.ti -1c
.RI "#define \fBMESSAGE_YELLOW_OFF\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBCDC_Transmit_FS\fP (uint8_t *Buf, uint16_t Len)"
.br
.RI "CDC_Transmit_FS Data to send over USB IN endpoint are sent over CDC interface through this function\&. "
.ti -1c
.RI "void \fBUSBD_CDC_IF_clear\fP (void)"
.br
.ti -1c
.RI "void \fBUSBD_CDC_IF_write\fP (void)"
.br
.ti -1c
.RI "int \fBUSBD_CDC_IF_procRcvData\fP (uint8_t *data, uint16_t size)"
.br
.ti -1c
.RI "int \fBUSBD_CDC_IF_analyzeRcvData\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_CDC_ItfTypeDef\fP \fBUSBD_Interface_fops_FS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: Header for \fBusbd_cdc_if\&.c\fP file\&. 


.PP
\fBVersion\fP
.RS 4
: v2\&.0_Cube
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 Donskih Dmitriy\&. All rights reserved\&."
.PP
This software component is licensed by Donskih Dmitriy under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Macro Definition Documentation"
.PP 
.SS "#define MESSAGE_YELLOW_OFF"
\fBValue:\fP
.PP
.nf
                                  "                    " \
                                    "                    " \
                                    "                    " \
                                    "      YELLOW OFF    "
.fi
.SS "#define MESSAGE_YELLOW_ON"
\fBValue:\fP
.PP
.nf
                                   "                    " \
                                    "                    " \
                                    "                    " \
                                    "      YELLOW ON     "
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
