.TH "USBD_EndpointTypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_EndpointTypeDef
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBstatus\fP"
.br
.ti -1c
.RI "uint32_t \fBis_used\fP"
.br
.ti -1c
.RI "uint32_t \fBtotal_length\fP"
.br
.ti -1c
.RI "uint32_t \fBrem_length\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxpacket\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
