.TH "USBD_CDC_IF_Exported_FunctionsPrototype" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC_IF_Exported_FunctionsPrototype \- USBD_CDC_IF_Exported_FunctionsPrototype
.PP
 \- Public functions declaration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBCDC_Transmit_FS\fP (uint8_t *Buf, uint16_t Len)"
.br
.RI "CDC_Transmit_FS Data to send over USB IN endpoint are sent over CDC interface through this function\&. "
.ti -1c
.RI "void \fBUSBD_CDC_IF_clear\fP (void)"
.br
.ti -1c
.RI "void \fBUSBD_CDC_IF_write\fP (void)"
.br
.ti -1c
.RI "int \fBUSBD_CDC_IF_procRcvData\fP (uint8_t *data, uint16_t size)"
.br
.ti -1c
.RI "int \fBUSBD_CDC_IF_analyzeRcvData\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Public functions declaration\&. 


.SH "Function Documentation"
.PP 
.SS "uint8_t CDC_Transmit_FS (uint8_t * Buf, uint16_t Len)"

.PP
CDC_Transmit_FS Data to send over USB IN endpoint are sent over CDC interface through this function\&. 
.PP
\fBNote\fP
.RS 4

.RE
.PP
\fBParameters\fP
.RS 4
\fIBuf\fP Buffer of data to be sent 
.br
\fILen\fP Number of data to be sent (in bytes) 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIUSBD_OK\fP if all operations are OK else USBD_FAIL or USBD_BUSY 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
