.TH "USBD_CORE" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CORE \- USBD_CORE
.PP
 \- This file is the Header file for \fBusbd_core\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_CORE_Exported_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Exported_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Exported_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Exported_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Exported_FunctionsPrototype\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Private_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Private_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Private_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Private_FunctionPrototypes\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Private_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_CORE_Private_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is the Header file for \fBusbd_core\&.c\fP file\&. 

usbd core module
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
