.TH "USBD_CDC_IF_Exported_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC_IF_Exported_Macros \- USBD_CDC_IF_Exported_Macros
.PP
 \- Aliases\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Aliases\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
