.TH "USBD_CDC_LineCodingTypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC_LineCodingTypeDef
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBbitrate\fP"
.br
.ti -1c
.RI "uint8_t \fBformat\fP"
.br
.ti -1c
.RI "uint8_t \fBparitytype\fP"
.br
.ti -1c
.RI "uint8_t \fBdatatype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
