.TH "USBD_DESC_Private_TypesDefinitions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC_Private_TypesDefinitions \- USBD_DESC_Private_TypesDefinitions
.PP
 \- Private types\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Private types\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
