.TH "USBD_DESC_Exported_TypesDefinitions" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC_Exported_TypesDefinitions \- USBD_DESC_Exported_TypesDefinitions
.PP
 \- Types\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Types\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
