.TH "USBD_CORE_Exported_Variables" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CORE_Exported_Variables \- USBD_CORE_Exported_Variables
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBD_CDC_CLASS\fP   &USBD_CDC"
.br
.ti -1c
.RI "#define \fBUSBD_SOF\fP   \fBUSBD_LL_SOF\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_ClassTypeDef\fP \fBUSBD_CDC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
