.TH "USBD_CDC_IF_Exported_Variables" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC_IF_Exported_Variables \- USBD_CDC_IF_Exported_Variables
.PP
 \- Public variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_CDC_ItfTypeDef\fP \fBUSBD_Interface_fops_FS\fP"
.br
.ti -1c
.RI "\fBUSBD_HandleTypeDef\fP \fBhUsbDeviceFS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Public variables\&. 


.SH "Variable Documentation"
.PP 
.SS "\fBUSBD_CDC_ItfTypeDef\fP USBD_Interface_fops_FS\fC [extern]\fP"
CDC Interface callback\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
