.TH "USBD_IOREQ" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_IOREQ \- USBD_IOREQ
.PP
 \- header file for the \fBusbd_ioreq\&.c\fP file  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_IOREQ_Exported_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Exported_Types\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Exported_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Exported_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Exported_FunctionsPrototype\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Private_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Private_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Private_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Private_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Private_FunctionPrototypes\fP"
.br
.ti -1c
.RI "\fBUSBD_IOREQ_Private_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
header file for the \fBusbd_ioreq\&.c\fP file 

control I/O requests module
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
