.TH "USBD_DEVICE_Exported_Variables" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DEVICE_Exported_Variables \- USBD_DEVICE_Exported_Variables
.PP
 \- Public variables\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Public variables\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
