.TH "USBD_DEVICE" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DEVICE \- USBD_DEVICE
.PP
 \- Device file for Usb otg low level driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_DEVICE_Exported_Variables\fP"
.br
.RI "Public variables\&. "
.ti -1c
.RI "\fBUSBD_DEVICE_Exported_FunctionsPrototype\fP"
.br
.RI "Declaration of public functions for Usb device\&. "
.in -1c
.SH "Detailed Description"
.PP 
Device file for Usb otg low level driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
