.TH "USBD_DESC_Private_Variables" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC_Private_Variables \- USBD_DESC_Private_Variables
.PP
 \- Private variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_DescriptorsTypeDef\fP \fBFS_Desc\fP"
.br
.ti -1c
.RI "__ALIGN_BEGIN uint8_t USBD_FS_DeviceDesc[USB_LEN_DEV_DESC] \fB__ALIGN_END\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Private variables\&. 


.SH "Variable Documentation"
.PP 
.SS "__ALIGN_BEGIN uint8_t USBD_StringSerial [USB_SIZ_STRING_SERIAL] __ALIGN_END"
\fBInitial value:\fP
.PP
.nf
=
{
  0x12,                       
  USB_DESC_TYPE_DEVICE,       
  0x00,                       
  0x02,
  0x02,                       
  0x02,                       
  0x00,                       
  USB_MAX_EP0_SIZE,           
  LOBYTE(USBD_VID),           
  HIBYTE(USBD_VID),           
  LOBYTE(USBD_PID_FS),        
  HIBYTE(USBD_PID_FS),        
  0x00,                       
  0x02,
  USBD_IDX_MFC_STR,           
  USBD_IDX_PRODUCT_STR,       
  USBD_IDX_SERIAL_STR,        
  USBD_MAX_NUM_CONFIGURATION  
}
.fi
USB standard device descriptor\&.
.PP
USB lang indentifier descriptor\&.
.PP
IAR Compiler 
.SS "\fBUSBD_DescriptorsTypeDef\fP FS_Desc"
\fBInitial value:\fP
.PP
.nf
=
{
  USBD_FS_DeviceDescriptor
, USBD_FS_LangIDStrDescriptor
, USBD_FS_ManufacturerStrDescriptor
, USBD_FS_ProductStrDescriptor
, USBD_FS_SerialStrDescriptor
, USBD_FS_ConfigStrDescriptor
, USBD_FS_InterfaceStrDescriptor
}
.fi
Descriptor for the Usb device\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
