.TH "USBD_DESC_Exported_Variables" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC_Exported_Variables \- USBD_DESC_Exported_Variables
.PP
 \- Public variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_DescriptorsTypeDef\fP \fBFS_Desc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Public variables\&. 


.SH "Variable Documentation"
.PP 
.SS "\fBUSBD_DescriptorsTypeDef\fP FS_Desc\fC [extern]\fP"
Descriptor for the Usb device\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
