.TH "usbd_cdc_Exported_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usbd_cdc_Exported_Defines \- Usbd_cdc_Exported_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCDC_IN_EP\fP   0x81U  /* EP1 for data IN */"
.br
.ti -1c
.RI "#define \fBCDC_OUT_EP\fP   0x01U  /* EP1 for data OUT */"
.br
.ti -1c
.RI "#define \fBCDC_CMD_EP\fP   0x82U  /* EP2 for CDC commands */"
.br
.ti -1c
.RI "#define \fBCDC_HS_BINTERVAL\fP   0x10U"
.br
.ti -1c
.RI "#define \fBCDC_FS_BINTERVAL\fP   0x10U"
.br
.ti -1c
.RI "#define \fBCDC_DATA_HS_MAX_PACKET_SIZE\fP   512U  /* Endpoint IN & OUT Packet size */"
.br
.ti -1c
.RI "#define \fBCDC_DATA_FS_MAX_PACKET_SIZE\fP   64U  /* Endpoint IN & OUT Packet size */"
.br
.ti -1c
.RI "#define \fBCDC_CMD_PACKET_SIZE\fP   8U  /* Control Endpoint Packet size */"
.br
.ti -1c
.RI "#define \fBUSB_CDC_CONFIG_DESC_SIZ\fP   67U"
.br
.ti -1c
.RI "#define \fBCDC_DATA_HS_IN_PACKET_SIZE\fP   CDC_DATA_HS_MAX_PACKET_SIZE"
.br
.ti -1c
.RI "#define \fBCDC_DATA_HS_OUT_PACKET_SIZE\fP   CDC_DATA_HS_MAX_PACKET_SIZE"
.br
.ti -1c
.RI "#define \fBCDC_DATA_FS_IN_PACKET_SIZE\fP   CDC_DATA_FS_MAX_PACKET_SIZE"
.br
.ti -1c
.RI "#define \fBCDC_DATA_FS_OUT_PACKET_SIZE\fP   CDC_DATA_FS_MAX_PACKET_SIZE"
.br
.ti -1c
.RI "#define \fBCDC_SEND_ENCAPSULATED_COMMAND\fP   0x00U"
.br
.ti -1c
.RI "#define \fBCDC_GET_ENCAPSULATED_RESPONSE\fP   0x01U"
.br
.ti -1c
.RI "#define \fBCDC_SET_COMM_FEATURE\fP   0x02U"
.br
.ti -1c
.RI "#define \fBCDC_GET_COMM_FEATURE\fP   0x03U"
.br
.ti -1c
.RI "#define \fBCDC_CLEAR_COMM_FEATURE\fP   0x04U"
.br
.ti -1c
.RI "#define \fBCDC_SET_LINE_CODING\fP   0x20U"
.br
.ti -1c
.RI "#define \fBCDC_GET_LINE_CODING\fP   0x21U"
.br
.ti -1c
.RI "#define \fBCDC_SET_CONTROL_LINE_STATE\fP   0x22U"
.br
.ti -1c
.RI "#define \fBCDC_SEND_BREAK\fP   0x23U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
