.TH "USBD_OTG_DRIVER" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_OTG_DRIVER \- USBD_OTG_DRIVER
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_DEVICE\fP"
.br
.RI "Device file for Usb otg low level driver\&. "
.ti -1c
.RI "\fBUSBD_CONF\fP"
.br
.RI "Configuration file for Usb otg low level driver\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
