.TH "USBD_DESC_Private_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC_Private_Defines \- USBD_DESC_Private_Defines
.PP
 \- Private defines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBD_VID\fP   1155"
.br
.ti -1c
.RI "#define \fBUSBD_LANGID_STRING\fP   1033"
.br
.ti -1c
.RI "#define \fBUSBD_MANUFACTURER_STRING\fP   'Git\-Video'"
.br
.ti -1c
.RI "#define \fBUSBD_PID_FS\fP   22336"
.br
.ti -1c
.RI "#define \fBUSBD_PRODUCT_STRING_FS\fP   'GDMX\-Info panel'"
.br
.ti -1c
.RI "#define \fBUSBD_CONFIGURATION_STRING_FS\fP   'CDC Config'"
.br
.ti -1c
.RI "#define \fBUSBD_INTERFACE_STRING_FS\fP   'CDC Interface'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Private defines\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
