.TH "vTaskPrioritySet" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vTaskPrioritySet \- vTaskPrioritySet
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h 
.PP
.nf
void vTaskPrioritySet( TaskHandle_t xTask, UBaseType_t uxNewPriority );
.fi
.PP
.PP
INCLUDE_vTaskPrioritySet must be defined as 1 for this function to be available\&. See the configuration section for more information\&.
.PP
Set the priority of any task\&.
.PP
A context switch will occur before the function returns if the priority being set is higher than the currently executing task\&.
.PP
\fBParameters\fP
.RS 4
\fIxTask\fP Handle to the task for which the priority is being set\&. Passing a NULL handle results in the priority of the calling task being set\&.
.br
\fIuxNewPriority\fP The priority to which the task will be set\&.
.RE
.PP
Example usage: 
.PP
.nf

void vAFunction( void )
{
TaskHandle_t xHandle;

    // Create a task, storing the handle\&.
    xTaskCreate( vTaskCode, 'NAME', STACK_SIZE, NULL, tskIDLE_PRIORITY, &xHandle );

    // \&.\&.\&.

    // Use the handle to raise the priority of the created task\&.
    vTaskPrioritySet( xHandle, tskIDLE_PRIORITY + 1 );

    // \&.\&.\&.

    // Use a NULL handle to raise our priority to the same value\&.
    vTaskPrioritySet( NULL, tskIDLE_PRIORITY + 1 );
}
  
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
