.TH "vTaskSuspend" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vTaskSuspend \- vTaskSuspend
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h 
.PP
.nf
void vTaskSuspend( TaskHandle_t xTaskToSuspend );
.fi
.PP
.PP
INCLUDE_vTaskSuspend must be defined as 1 for this function to be available\&. See the configuration section for more information\&.
.PP
Suspend any task\&. When suspended a task will never get any microcontroller processing time, no matter what its priority\&.
.PP
Calls to vTaskSuspend are not accumulative - i\&.e\&. calling vTaskSuspend () twice on the same task still only requires one call to vTaskResume () to ready the suspended task\&.
.PP
\fBParameters\fP
.RS 4
\fIxTaskToSuspend\fP Handle to the task being suspended\&. Passing a NULL handle will cause the calling task to be suspended\&.
.RE
.PP
Example usage: 
.PP
.nf

void vAFunction( void )
{
TaskHandle_t xHandle;

    // Create a task, storing the handle\&.
    xTaskCreate( vTaskCode, 'NAME', STACK_SIZE, NULL, tskIDLE_PRIORITY, &xHandle );

    // \&.\&.\&.

    // Use the handle to suspend the created task\&.
    vTaskSuspend( xHandle );

    // \&.\&.\&.

    // The created task will not run during this period, unless
    // another task calls vTaskResume( xHandle )\&.

    //\&.\&.\&.


    // Suspend ourselves\&.
    vTaskSuspend( NULL );

    // We cannot get here unless another task calls vTaskResume
    // with our handle as the parameter\&.
}
  
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
