.TH "vTaskDelay" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vTaskDelay \- vTaskDelay
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h 
.PP
.nf
void vTaskDelay( const TickType_t xTicksToDelay );
.fi
.PP
.PP
Delay a task for a given number of ticks\&. The actual time that the task remains blocked depends on the tick rate\&. The constant portTICK_PERIOD_MS can be used to calculate real time from the tick rate - with the resolution of one tick period\&.
.PP
INCLUDE_vTaskDelay must be defined as 1 for this function to be available\&. See the configuration section for more information\&.
.PP
vTaskDelay() specifies a time at which the task wishes to unblock relative to the time at which vTaskDelay() is called\&. For example, specifying a block period of 100 ticks will cause the task to unblock 100 ticks after vTaskDelay() is called\&. vTaskDelay() does not therefore provide a good method of controlling the frequency of a periodic task as the path taken through the code, as well as other task and interrupt activity, will effect the frequency at which vTaskDelay() gets called and therefore the time at which the task next executes\&. See vTaskDelayUntil() for an alternative API function designed to facilitate fixed frequency execution\&. It does this by specifying an absolute time (rather than a relative time) at which the calling task should unblock\&.
.PP
\fBParameters\fP
.RS 4
\fIxTicksToDelay\fP The amount of time, in tick periods, that the calling task should block\&.
.RE
.PP
Example usage:
.PP
void vTaskFunction( void * pvParameters ) { Block for 500ms\&. const TickType_t xDelay = 500 / portTICK_PERIOD_MS; 
.PP
.nf
for( ;; )
{

.fi
.PP
 Simply toggle the LED every 500ms, blocking between each toggle\&. vToggleLED(); vTaskDelay( xDelay ); } } 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
