.TH "xLIST" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xLIST
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "listFIRST_LIST_INTEGRITY_CHECK_VALUE volatile UBaseType_t \fBuxNumberOfItems\fP"
.br
.ti -1c
.RI "\fBListItem_t\fP *configLIST_VOLATILE \fBpxIndex\fP"
.br
.ti -1c
.RI "\fBMiniListItem_t\fP \fBxListEnd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
