.TH "xMessageBufferReceive" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xMessageBufferReceive \- xMessageBufferReceive
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBmessage_buffer\&.h\fP
.PP
.PP
.nf

size_t xMessageBufferReceive( MessageBufferHandle_t xMessageBuffer,
                              void *pvRxData,
                              size_t xBufferLengthBytes,
                              TickType_t xTicksToWait );
.fi
.PP
.PP
Receives a discrete message from a message buffer\&. Messages can be of variable length and are copied out of the buffer\&.
.PP
\fI\fBNOTE\fP\fP: Uniquely among FreeRTOS objects, the stream buffer implementation (so also the message buffer implementation, as message buffers are built on top of stream buffers) assumes there is only one task or interrupt that will write to the buffer (the writer), and only one task or interrupt that will read from the buffer (the reader)\&. It is safe for the writer and reader to be different tasks or interrupts, but, unlike other FreeRTOS objects, it is not safe to have multiple different writers or multiple different readers\&. If there are to be multiple different writers then the application writer must place each call to a writing API function (such as xMessageBufferSend()) inside a critical section and set the send block time to 0\&. Likewise, if there are to be multiple different readers then the application writer must place each call to a reading API function (such as xMessageBufferRead()) inside a critical section and set the receive block time to 0\&.
.PP
Use xMessageBufferReceive() to read from a message buffer from a task\&. Use xMessageBufferReceiveFromISR() to read from a message buffer from an interrupt service routine (ISR)\&.
.PP
\fBParameters\fP
.RS 4
\fIxMessageBuffer\fP The handle of the message buffer from which a message is being received\&.
.br
\fIpvRxData\fP A pointer to the buffer into which the received message is to be copied\&.
.br
\fIxBufferLengthBytes\fP The length of the buffer pointed to by the pvRxData parameter\&. This sets the maximum length of the message that can be received\&. If xBufferLengthBytes is too small to hold the next message then the message will be left in the message buffer and 0 will be returned\&.
.br
\fIxTicksToWait\fP The maximum amount of time the task should remain in the Blocked state to wait for a message, should the message buffer be empty\&. xMessageBufferReceive() will return immediately if xTicksToWait is zero and the message buffer is empty\&. The block time is specified in tick periods, so the absolute time it represents is dependent on the tick frequency\&. The macro pdMS_TO_TICKS() can be used to convert a time specified in milliseconds into a time specified in ticks\&. Setting xTicksToWait to portMAX_DELAY will cause the task to wait indefinitely (without timing out), provided INCLUDE_vTaskSuspend is set to 1 in \fBFreeRTOSConfig\&.h\fP\&. Tasks do not use any CPU time when they are in the Blocked state\&.
.RE
.PP
\fBReturns\fP
.RS 4
The length, in bytes, of the message read from the message buffer, if any\&. If xMessageBufferReceive() times out before a message became available then zero is returned\&. If the length of the message is greater than xBufferLengthBytes then the message will be left in the message buffer and zero is returned\&.
.RE
.PP
Example use: 
.PP
.nf

void vAFunction( MessageBuffer_t xMessageBuffer )
{
uint8_t ucRxData[ 20 ];
size_t xReceivedBytes;
const TickType_t xBlockTime = pdMS_TO_TICKS( 20 );

    // Receive the next message from the message buffer\&.  Wait in the Blocked
    // state (so not using any CPU processing time) for a maximum of 100ms for
    // a message to become available\&.
    xReceivedBytes = xMessageBufferReceive( xMessageBuffer,
                                            ( void * ) ucRxData,
                                            sizeof( ucRxData ),
                                            xBlockTime );

    if( xReceivedBytes > 0 )
    {
        // A ucRxData contains a message that is xReceivedBytes long\&.  Process
        // the message here\&.\&.\&.\&.
    }
}
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
