.TH "xMessageBufferReset" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xMessageBufferReset \- xMessageBufferReset
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBmessage_buffer\&.h\fP 
.PP
.nf

BaseType_t xMessageBufferReset( MessageBufferHandle_t xMessageBuffer );
.fi
.PP
.PP
Resets a message buffer to its initial empty state, discarding any message it contained\&.
.PP
A message buffer can only be reset if there are no tasks blocked on it\&.
.PP
\fBParameters\fP
.RS 4
\fIxMessageBuffer\fP The handle of the message buffer being reset\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the message buffer was reset then pdPASS is returned\&. If the message buffer could not be reset because either there was a task blocked on the message queue to wait for space to become available, or to wait for a a message to be available, then pdFAIL is returned\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
