.TH "xSTATIC_EVENT_GROUP" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xSTATIC_EVENT_GROUP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TickType_t \fBxDummy1\fP"
.br
.ti -1c
.RI "\fBStaticList_t\fP \fBxDummy2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
