.TH "xSTATIC_QUEUE" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xSTATIC_QUEUE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpvDummy1\fP [3]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   void * \fBpvDummy2\fP"
.br
.ti -1c
.RI "   UBaseType_t \fBuxDummy2\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "\fBStaticList_t\fP \fBxDummy3\fP [2]"
.br
.ti -1c
.RI "UBaseType_t \fBuxDummy4\fP [3]"
.br
.ti -1c
.RI "uint8_t \fBucDummy5\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
