.TH "xSTREAM_BUFFER" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xSTREAM_BUFFER
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile size_t \fBxTail\fP"
.br
.ti -1c
.RI "volatile size_t \fBxHead\fP"
.br
.ti -1c
.RI "size_t \fBxLength\fP"
.br
.ti -1c
.RI "size_t \fBxTriggerLevelBytes\fP"
.br
.ti -1c
.RI "volatile TaskHandle_t \fBxTaskWaitingToReceive\fP"
.br
.ti -1c
.RI "volatile TaskHandle_t \fBxTaskWaitingToSend\fP"
.br
.ti -1c
.RI "uint8_t * \fBpucBuffer\fP"
.br
.ti -1c
.RI "uint8_t \fBucFlags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
