.TH "xStreamBufferBytesAvailable" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xStreamBufferBytesAvailable \- xStreamBufferBytesAvailable
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBstream_buffer\&.h\fP
.PP
.PP
.nf

size_t xStreamBufferBytesAvailable( StreamBufferHandle_t xStreamBuffer );
.fi
.PP
.PP
Queries a stream buffer to see how much data it contains, which is equal to the number of bytes that can be read from the stream buffer before the stream buffer would be empty\&.
.PP
\fBParameters\fP
.RS 4
\fIxStreamBuffer\fP The handle of the stream buffer being queried\&.
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes that can be read from the stream buffer before the stream buffer would be empty\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
