.TH "xStreamBufferIsFull" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xStreamBufferIsFull \- xStreamBufferIsFull
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBstream_buffer\&.h\fP
.PP
.PP
.nf

BaseType_t xStreamBufferIsFull( StreamBufferHandle_t xStreamBuffer );
.fi
.PP
.PP
Queries a stream buffer to see if it is full\&. A stream buffer is full if it does not have any free space, and therefore cannot accept any more data\&.
.PP
\fBParameters\fP
.RS 4
\fIxStreamBuffer\fP The handle of the stream buffer being queried\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the stream buffer is full then pdTRUE is returned\&. Otherwise pdFALSE is returned\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
