.TH "xTaskNotifyStateClear" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xTaskNotifyStateClear \- xTaskNotifyStateClear
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h 
.PP
.nf
BaseType_t xTaskNotifyStateClear( TaskHandle_t xTask );
.fi
.PP
.PP
If the notification state of the task referenced by the handle xTask is eNotified, then set the task's notification state to eNotWaitingNotification\&. The task's notification value is not altered\&. Set xTask to NULL to clear the notification state of the calling task\&.
.PP
\fBReturns\fP
.RS 4
pdTRUE if the task's notification state was set to eNotWaitingNotification, otherwise pdFALSE\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
