.TH "xTaskGetTickCountFromISR" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xTaskGetTickCountFromISR \- xTaskGetTickCountFromISR
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h 
.PP
.nf
TickType_t xTaskGetTickCountFromISR( void );
.fi
.PP
.PP
\fBReturns\fP
.RS 4
The count of ticks since vTaskStartScheduler was called\&.
.RE
.PP
This is a version of xTaskGetTickCount() that is safe to be called from an ISR - provided that TickType_t is the natural word size of the microcontroller being used or interrupt nesting is either not supported or not being used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
