.TH "xTIME_OUT" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xTIME_OUT
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "BaseType_t \fBxOverflowCount\fP"
.br
.ti -1c
.RI "TickType_t \fBxTimeOnEntering\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
