.TH "AFIO_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFIO_TypeDef \- Alternate Function I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEVCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMAPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEXTICR\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMAPR2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Alternate Function I/O\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
