.TH "CAN_TxMailBox_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_TxMailBox_TypeDef \- Controller Area Network TxMailBox\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDHR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller Area Network TxMailBox\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
