.TH "DMA_Channel_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Channel_TypeDef \- DMA Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCPAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DMA Controller\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
