.TH "DMAEx_Exported_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx_Exported_Macros \- DMA Extended Exported Macros
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDMA Low density and Medium density product devices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
