.TH "EXTI_Line" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Line \- EXTI Line
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXTI_LINE_0\fP   (EXTI_GPIO     | 0x00u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_1\fP   (EXTI_GPIO     | 0x01u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_2\fP   (EXTI_GPIO     | 0x02u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_3\fP   (EXTI_GPIO     | 0x03u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_4\fP   (EXTI_GPIO     | 0x04u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_5\fP   (EXTI_GPIO     | 0x05u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_6\fP   (EXTI_GPIO     | 0x06u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_7\fP   (EXTI_GPIO     | 0x07u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_8\fP   (EXTI_GPIO     | 0x08u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_9\fP   (EXTI_GPIO     | 0x09u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_10\fP   (EXTI_GPIO     | 0x0Au)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_11\fP   (EXTI_GPIO     | 0x0Bu)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_12\fP   (EXTI_GPIO     | 0x0Cu)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_13\fP   (EXTI_GPIO     | 0x0Du)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_14\fP   (EXTI_GPIO     | 0x0Eu)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_15\fP   (EXTI_GPIO     | 0x0Fu)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_16\fP   (EXTI_CONFIG   | 0x10u)"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_17\fP   (EXTI_CONFIG   | 0x11u)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTI_LINE_0   (EXTI_GPIO     | 0x00u)"
External interrupt line 0 
.SS "#define EXTI_LINE_1   (EXTI_GPIO     | 0x01u)"
External interrupt line 1 
.SS "#define EXTI_LINE_10   (EXTI_GPIO     | 0x0Au)"
External interrupt line 10 
.SS "#define EXTI_LINE_11   (EXTI_GPIO     | 0x0Bu)"
External interrupt line 11 
.SS "#define EXTI_LINE_12   (EXTI_GPIO     | 0x0Cu)"
External interrupt line 12 
.SS "#define EXTI_LINE_13   (EXTI_GPIO     | 0x0Du)"
External interrupt line 13 
.SS "#define EXTI_LINE_14   (EXTI_GPIO     | 0x0Eu)"
External interrupt line 14 
.SS "#define EXTI_LINE_15   (EXTI_GPIO     | 0x0Fu)"
External interrupt line 15 
.SS "#define EXTI_LINE_16   (EXTI_CONFIG   | 0x10u)"
External interrupt line 16 Connected to the PVD Output 
.SS "#define EXTI_LINE_17   (EXTI_CONFIG   | 0x11u)"
External interrupt line 17 Connected to the RTC Alarm event 
.SS "#define EXTI_LINE_2   (EXTI_GPIO     | 0x02u)"
External interrupt line 2 
.SS "#define EXTI_LINE_3   (EXTI_GPIO     | 0x03u)"
External interrupt line 3 
.SS "#define EXTI_LINE_4   (EXTI_GPIO     | 0x04u)"
External interrupt line 4 
.SS "#define EXTI_LINE_5   (EXTI_GPIO     | 0x05u)"
External interrupt line 5 
.SS "#define EXTI_LINE_6   (EXTI_GPIO     | 0x06u)"
External interrupt line 6 
.SS "#define EXTI_LINE_7   (EXTI_GPIO     | 0x07u)"
External interrupt line 7 
.SS "#define EXTI_LINE_8   (EXTI_GPIO     | 0x08u)"
External interrupt line 8 
.SS "#define EXTI_LINE_9   (EXTI_GPIO     | 0x09u)"
External interrupt line 9 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
