.TH "FLASH_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_TypeDef \- FLASH Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBACR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOPTKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRESERVED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOBR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWRPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FLASH Registers\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
