.TH "FLASH_Exported_Types" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Exported_Types \- FLASH Exported Types
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFLASH_ProcessTypeDef\fP"
.br
.RI "FLASH handle Structure definition 
.br
 "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFLASH_ProcedureTypeDef\fP { \fBFLASH_PROC_NONE\fP = 0U, \fBFLASH_PROC_PAGEERASE\fP = 1U, \fBFLASH_PROC_MASSERASE\fP = 2U, \fBFLASH_PROC_PROGRAMHALFWORD\fP = 3U, \fBFLASH_PROC_PROGRAMWORD\fP = 4U, \fBFLASH_PROC_PROGRAMDOUBLEWORD\fP = 5U }"
.br
.RI "FLASH Procedure structure definition\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
