.TH "GPIOEx_Exported_Functions_Group1" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOEx_Exported_Functions_Group1 \- GPIOEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_GPIOEx_ConfigEventout\fP (uint32_t GPIO_PortSource, uint32_t GPIO_PinSource)"
.br
.ti -1c
.RI "void \fBHAL_GPIOEx_EnableEventout\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_GPIOEx_DisableEventout\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
