.TH "GPIO_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_TypeDef \- General Purpose I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBODR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBSRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLCKR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General Purpose I/O\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
