.TH "HAL_SYSCFG_Aliased_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SYSCFG_Aliased_Defines \- HAL SYSCFG Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PA9\fP   I2C_FASTMODEPLUS_PA9"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PA10\fP   I2C_FASTMODEPLUS_PA10"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB6\fP   I2C_FASTMODEPLUS_PB6"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB7\fP   I2C_FASTMODEPLUS_PB7"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB8\fP   I2C_FASTMODEPLUS_PB8"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB9\fP   I2C_FASTMODEPLUS_PB9"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C1\fP   I2C_FASTMODEPLUS_I2C1"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C2\fP   I2C_FASTMODEPLUS_I2C2"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C3\fP   I2C_FASTMODEPLUS_I2C3"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
