.TH "HAL_GPIO_Aliased_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_GPIO_Aliased_Macros \- HAL GPIO Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGET_GPIO_SOURCE\fP   GPIO_GET_INDEX"
.br
.ti -1c
.RI "#define \fBGET_GPIO_INDEX\fP   GPIO_GET_INDEX"
.br
.ti -1c
.RI "#define \fBGPIO_AF0_LPTIM\fP   GPIO_AF0_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF1_LPTIM\fP   GPIO_AF1_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF2_LPTIM\fP   GPIO_AF2_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF6_DFSDM\fP   GPIO_AF6_DFSDM1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
