.TH "HAL_ETH_Aliased_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_ETH_Aliased_Defines \- HAL ETH Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVLAN_TAG\fP   ETH_VLAN_TAG"
.br
.ti -1c
.RI "#define \fBMIN_ETH_PAYLOAD\fP   ETH_MIN_ETH_PAYLOAD"
.br
.ti -1c
.RI "#define \fBMAX_ETH_PAYLOAD\fP   ETH_MAX_ETH_PAYLOAD"
.br
.ti -1c
.RI "#define \fBJUMBO_FRAME_PAYLOAD\fP   ETH_JUMBO_FRAME_PAYLOAD"
.br
.ti -1c
.RI "#define \fBMACMIIAR_CR_MASK\fP   ETH_MACMIIAR_CR_MASK"
.br
.ti -1c
.RI "#define \fBMACCR_CLEAR_MASK\fP   ETH_MACCR_CLEAR_MASK"
.br
.ti -1c
.RI "#define \fBMACFCR_CLEAR_MASK\fP   ETH_MACFCR_CLEAR_MASK"
.br
.ti -1c
.RI "#define \fBDMAOMR_CLEAR_MASK\fP   ETH_DMAOMR_CLEAR_MASK"
.br
.ti -1c
.RI "#define \fBETH_MMCCR\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBETH_MMCRIR\fP   0x00000104U"
.br
.ti -1c
.RI "#define \fBETH_MMCTIR\fP   0x00000108U"
.br
.ti -1c
.RI "#define \fBETH_MMCRIMR\fP   0x0000010CU"
.br
.ti -1c
.RI "#define \fBETH_MMCTIMR\fP   0x00000110U"
.br
.ti -1c
.RI "#define \fBETH_MMCTGFSCCR\fP   0x0000014CU"
.br
.ti -1c
.RI "#define \fBETH_MMCTGFMSCCR\fP   0x00000150U"
.br
.ti -1c
.RI "#define \fBETH_MMCTGFCR\fP   0x00000168U"
.br
.ti -1c
.RI "#define \fBETH_MMCRFCECR\fP   0x00000194U"
.br
.ti -1c
.RI "#define \fBETH_MMCRFAECR\fP   0x00000198U"
.br
.ti -1c
.RI "#define \fBETH_MMCRGUFCR\fP   0x000001C4U"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFO_FULL\fP   0x02000000U  /* Tx FIFO full */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFONOT_EMPTY\fP   0x01000000U  /* Tx FIFO not empty */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFO_WRITE_ACTIVE\fP   0x00400000U  /* Tx FIFO write active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFO_IDLE\fP   0x00000000U  /* Tx FIFO read status: Idle */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFO_READ\fP   0x00100000U  /* Tx FIFO read status: Read (transferring data to the MAC transmitter) */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFO_WAITING\fP   0x00200000U  /* Tx FIFO read status: Waiting for TxStatus from MAC transmitter */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TXFIFO_WRITING\fP   0x00300000U  /* Tx FIFO read status: Writing the received TxStatus or flushing the TxFIFO */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TRANSMISSION_PAUSE\fP   0x00080000U  /* MAC transmitter in pause */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TRANSMITFRAMECONTROLLER_IDLE\fP   0x00000000U  /* MAC transmit frame controller: Idle */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TRANSMITFRAMECONTROLLER_WAITING\fP   0x00020000U  /* MAC transmit frame controller: Waiting for Status of previous frame or IFG/backoff period to be over */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TRANSMITFRAMECONTROLLER_GENRATING_PCF\fP   0x00040000U  /* MAC transmit frame controller: Generating and transmitting a Pause control frame (in full duplex mode) */"
.br
.ti -1c
.RI "#define \fBETH_MAC_TRANSMITFRAMECONTROLLER_TRANSFERRING\fP   0x00060000U  /* MAC transmit frame controller: Transferring input frame for transmission */"
.br
.ti -1c
.RI "#define \fBETH_MAC_MII_TRANSMIT_ACTIVE\fP   0x00010000U  /* MAC MII transmit engine active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_RXFIFO_EMPTY\fP   0x00000000U  /* Rx FIFO fill level: empty */"
.br
.ti -1c
.RI "#define \fBETH_MAC_RXFIFO_BELOW_THRESHOLD\fP   0x00000100U  /* Rx FIFO fill level: fill\-level below flow\-control de\-activate threshold */"
.br
.ti -1c
.RI "#define \fBETH_MAC_RXFIFO_ABOVE_THRESHOLD\fP   0x00000200U  /* Rx FIFO fill level: fill\-level above flow\-control activate threshold */"
.br
.ti -1c
.RI "#define \fBETH_MAC_RXFIFO_FULL\fP   0x00000300U  /* Rx FIFO fill level: full */"
.br
.ti -1c
.RI "#define \fBETH_MAC_READCONTROLLER_IDLE\fP   0x00000000U  /* Rx FIFO read controller IDLE state */"
.br
.ti -1c
.RI "#define \fBETH_MAC_READCONTROLLER_READING_DATA\fP   0x00000020U  /* Rx FIFO read controller Reading frame data */"
.br
.ti -1c
.RI "#define \fBETH_MAC_READCONTROLLER_READING_STATUS\fP   0x00000040U  /* Rx FIFO read controller Reading frame status (or time\-stamp) */"
.br
.ti -1c
.RI "#define \fBETH_MAC_READCONTROLLER_FLUSHING\fP   0x00000060U  /* Rx FIFO read controller Flushing the frame data and status */"
.br
.ti -1c
.RI "#define \fBETH_MAC_RXFIFO_WRITE_ACTIVE\fP   0x00000010U  /* Rx FIFO write controller active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_SMALL_FIFO_NOTACTIVE\fP   0x00000000U  /* MAC small FIFO read / write controllers not active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_SMALL_FIFO_READ_ACTIVE\fP   0x00000002U  /* MAC small FIFO read controller active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_SMALL_FIFO_WRITE_ACTIVE\fP   0x00000004U  /* MAC small FIFO write controller active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_SMALL_FIFO_RW_ACTIVE\fP   0x00000006U  /* MAC small FIFO read / write controllers active */"
.br
.ti -1c
.RI "#define \fBETH_MAC_MII_RECEIVE_PROTOCOL_ACTIVE\fP   0x00000001U  /* MAC MII receive protocol engine active */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
