.TH "HAL_LTDC_Aliased_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_LTDC_Aliased_Macros \- HAL LTDC Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_LTDC_LAYER\fP   LTDC_LAYER"
.br
.ti -1c
.RI "#define \fB__HAL_LTDC_RELOAD_CONFIG\fP   __HAL_LTDC_RELOAD_IMMEDIATE_CONFIG"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
