.TH "HAL_LPTIM_Aliased_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_LPTIM_Aliased_Defines \- HAL LPTIM Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_DIRECTTRANSISTION\fP   LPTIM_CLOCKSAMPLETIME_DIRECTTRANSITION"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_2TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_4TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_8TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_8TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_RISINGEDGE\fP   LPTIM_CLOCKPOLARITY_RISING"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_FALLINGEDGE\fP   LPTIM_CLOCKPOLARITY_FALLING"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_BOTHEDGES\fP   LPTIM_CLOCKPOLARITY_RISING_FALLING"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_DIRECTTRANSISTION\fP   LPTIM_TRIGSAMPLETIME_DIRECTTRANSITION"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_2TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_4TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_8TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_2TRANSITION\fP   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_4TRANSITION\fP   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_8TRANSITION\fP   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
