.TH "I2C_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_TypeDef \- Inter Integrated Circuit Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOAR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOAR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTRISE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inter Integrated Circuit Interface\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
