.TH "OB_TypeDef" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OB_TypeDef \- Option Bytes Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103xb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRDP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBUSER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBData0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBData1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Option Bytes Registers\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
