.TH "os_pool_def" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
os_pool_def
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_os\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBpool_sz\fP"
.br
.RI "number of items (elements) in the pool "
.ti -1c
.RI "uint32_t \fBitem_sz\fP"
.br
.RI "size of an item "
.ti -1c
.RI "void * \fBpool\fP"
.br
.RI "pointer to memory for pool "
.in -1c
.SH "Detailed Description"
.PP 
Definition structure for memory block allocation\&. 
.PP
\fBNote\fP
.RS 4
CAN BE CHANGED: \fB\fBos_pool_def\fP\fP is implementation specific in every CMSIS-RTOS\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
