.TH "os_thread_def" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
os_thread_def
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_os\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.RI "Thread name\&. "
.ti -1c
.RI "os_pthread \fBpthread\fP"
.br
.RI "start address of thread function "
.ti -1c
.RI "osPriority \fBtpriority\fP"
.br
.RI "initial thread priority "
.ti -1c
.RI "uint32_t \fBinstances\fP"
.br
.RI "maximum number of instances of that thread function "
.ti -1c
.RI "uint32_t \fBstacksize\fP"
.br
.RI "stack size requirements in bytes; 0 is default stack size "
.in -1c
.SH "Detailed Description"
.PP 
Thread Definition structure contains startup information of a thread\&. 
.PP
\fBNote\fP
.RS 4
CAN BE CHANGED: \fB\fBos_thread_def\fP\fP is implementation specific in every CMSIS-RTOS\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
