.TH "PWR" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR \- PWR
.PP
 \- PWR HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPWR Exported Types\fP"
.br
.ti -1c
.RI "\fBPWR Exported Constants\fP"
.br
.ti -1c
.RI "\fBPWR Exported Macros\fP"
.br
.ti -1c
.RI "\fBPWR Private Macros\fP"
.br
.ti -1c
.RI "\fBPWR_Private_Constants\fP"
.br
.ti -1c
.RI "\fBPWR Exported Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PWR HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
