.TH "STM32_USBD_DEVICE_LIBRARY" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32_USBD_DEVICE_LIBRARY \- STM32_USBD_DEVICE_LIBRARY
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSB_DEF\fP"
.br
.RI "general defines for the usb device library file "
.ti -1c
.RI "\fBUSBD_CORE\fP"
.br
.RI "This file is the Header file for \fBusbd_core\&.c\fP file\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
