.TH "STM32F1xx_System_Private_Defines" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F1xx_System_Private_Defines \- STM32F1xx_System_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   8000000U"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   8000000U"
.br
.ti -1c
.RI "#define \fBVECT_TAB_OFFSET\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HSE_VALUE   8000000U"
Default value of the External oscillator in Hz\&. This value can be provided and adapted by the user application\&. 
.SS "#define HSI_VALUE   8000000U"
Default value of the Internal oscillator in Hz\&. This value can be provided and adapted by the user application\&. 
.SS "#define VECT_TAB_OFFSET   0x00000000U"
< Uncomment the following line if you need to use external SRAM 
.br
.PP
< Uncomment the following line if you need to relocate your vector Table in Internal SRAM\&. Vector Table base offset field\&. This value must be a multiple of 0x200\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
