.TH "USB_DEF" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB_DEF \- USB_DEF
.PP
 \- general defines for the usb device library file  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSB_DEF_Exported_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_DEF_Exported_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBUSBD_DEF_Exported_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_DEF_Exported_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_DEF_Exported_FunctionsPrototype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
general defines for the usb device library file 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
