.TH "USBD_CDC" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CDC \- USBD_CDC
.PP
 \- usbd core module  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_CDC_Private_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBUSBD_CDC_Private_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_CDC_Private_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_CDC_Private_FunctionPrototypes\fP"
.br
.ti -1c
.RI "\fBUSBD_CDC_Private_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_CDC_Private_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
usbd core module 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
