.TH "USBD_DESC_Exported_Constants" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC_Exported_Constants \- USBD_DESC_Exported_Constants
.PP
 \- Constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEVICE_ID1\fP   (\fBUID_BASE\fP)"
.br
.ti -1c
.RI "#define \fBDEVICE_ID2\fP   (\fBUID_BASE\fP + 0x4)"
.br
.ti -1c
.RI "#define \fBDEVICE_ID3\fP   (\fBUID_BASE\fP + 0x8)"
.br
.ti -1c
.RI "#define \fBUSB_SIZ_STRING_SERIAL\fP   0x1A"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constants\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
