.TH "USBD_CONF" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_CONF \- USBD_CONF
.PP
 \- Configuration file for Usb otg low level driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_CONF_Exported_Variables\fP"
.br
.RI "Public variables\&. "
.ti -1c
.RI "\fBUSBD_CONF_Exported_Defines\fP"
.br
.RI "Defines for configuration of the Usb device\&. "
.ti -1c
.RI "\fBUSBD_CONF_Exported_Macros\fP"
.br
.RI "Aliases\&. "
.ti -1c
.RI "\fBUSBD_CONF_Exported_Types\fP"
.br
.RI "Types\&. "
.ti -1c
.RI "\fBUSBD_CONF_Exported_FunctionsPrototype\fP"
.br
.RI "Declaration of public functions for Usb device\&. "
.in -1c
.SH "Detailed Description"
.PP 
Configuration file for Usb otg low level driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
