.TH "USBD_REQ" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_REQ \- USBD_REQ
.PP
 \- header file for the usbd_req\&.c file  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_REQ_Exported_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Exported_Types\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Exported_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Exported_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Exported_FunctionsPrototype\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Private_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Private_Defines\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Private_Macros\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Private_Variables\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Private_FunctionPrototypes\fP"
.br
.ti -1c
.RI "\fBUSBD_REQ_Private_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
header file for the usbd_req\&.c file 

USB standard requests module\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
