.TH "USBD_DEVICE_Exported_FunctionsPrototype" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DEVICE_Exported_FunctionsPrototype \- USBD_DEVICE_Exported_FunctionsPrototype
.PP
 \- Declaration of public functions for Usb device\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_USB_DEVICE_Init\fP (void)"
.br
.RI "MX USB Device library initialization function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of public functions for Usb device\&. 


.SH "Function Documentation"
.PP 
.SS "void MX_USB_DEVICE_Init (void)"

.PP
MX USB Device library initialization function\&. USB Device initialization function\&.
.PP
Init USB device Library, add supported class and start the library\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
