.TH "Src/usbd_desc.c" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/usbd_desc.c \- : Header for \fBusbd_conf\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'usbd_core\&.h'\fP
.br
\fC#include 'usbd_desc\&.h'\fP
.br
\fC#include 'usbd_conf\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBD_VID\fP   1155"
.br
.ti -1c
.RI "#define \fBUSBD_LANGID_STRING\fP   1033"
.br
.ti -1c
.RI "#define \fBUSBD_MANUFACTURER_STRING\fP   'Git\-Video'"
.br
.ti -1c
.RI "#define \fBUSBD_PID_FS\fP   22336"
.br
.ti -1c
.RI "#define \fBUSBD_PRODUCT_STRING_FS\fP   'GDMX\-Info panel'"
.br
.ti -1c
.RI "#define \fBUSBD_CONFIGURATION_STRING_FS\fP   'CDC Config'"
.br
.ti -1c
.RI "#define \fBUSBD_INTERFACE_STRING_FS\fP   'CDC Interface'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t * \fBUSBD_FS_DeviceDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the device descriptor\&. "
.ti -1c
.RI "uint8_t * \fBUSBD_FS_LangIDStrDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the LangID string descriptor\&. "
.ti -1c
.RI "uint8_t * \fBUSBD_FS_ManufacturerStrDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the manufacturer string descriptor\&. "
.ti -1c
.RI "uint8_t * \fBUSBD_FS_ProductStrDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the product string descriptor\&. "
.ti -1c
.RI "uint8_t * \fBUSBD_FS_SerialStrDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the serial number string descriptor\&. "
.ti -1c
.RI "uint8_t * \fBUSBD_FS_ConfigStrDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the configuration string descriptor\&. "
.ti -1c
.RI "uint8_t * \fBUSBD_FS_InterfaceStrDescriptor\fP (USBD_SpeedTypeDef speed, uint16_t *length)"
.br
.RI "Return the interface string descriptor\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUSBD_DescriptorsTypeDef\fP \fBFS_Desc\fP"
.br
.ti -1c
.RI "__ALIGN_BEGIN uint8_t USBD_FS_DeviceDesc[USB_LEN_DEV_DESC] \fB__ALIGN_END\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: Header for \fBusbd_conf\&.c\fP file\&. 

: This file implements the USB device descriptors\&.
.PP
\fBVersion\fP
.RS 4
: v2\&.0_Cube
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 Donskih Dmitriy\&. All rights reserved\&."
.PP
This software component is licensed by Donskih Dmitriy under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
