.TH "USBD_DESC" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DESC \- USBD_DESC
.PP
 \- Usb device descriptors module\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUSBD_DESC_Exported_Constants\fP"
.br
.RI "Constants\&. "
.ti -1c
.RI "\fBUSBD_DESC_Exported_Defines\fP"
.br
.RI "Defines\&. "
.ti -1c
.RI "\fBUSBD_DESC_Exported_TypesDefinitions\fP"
.br
.RI "Types\&. "
.ti -1c
.RI "\fBUSBD_DESC_Exported_Macros\fP"
.br
.RI "Aliases\&. "
.ti -1c
.RI "\fBUSBD_DESC_Exported_Variables\fP"
.br
.RI "Public variables\&. "
.ti -1c
.RI "\fBUSBD_DESC_Exported_FunctionsPrototype\fP"
.br
.RI "Public functions declaration\&. "
.ti -1c
.RI "\fBUSBD_DESC_Private_TypesDefinitions\fP"
.br
.RI "Private types\&. "
.ti -1c
.RI "\fBUSBD_DESC_Private_Defines\fP"
.br
.RI "Private defines\&. "
.ti -1c
.RI "\fBUSBD_DESC_Private_Macros\fP"
.br
.RI "Private macros\&. "
.ti -1c
.RI "\fBUSBD_DESC_Private_FunctionPrototypes\fP"
.br
.RI "Private functions declaration\&. "
.ti -1c
.RI "\fBUSBD_DESC_Private_Variables\fP"
.br
.RI "Private variables\&. "
.ti -1c
.RI "\fBUSBD_DESC_Private_Functions\fP"
.br
.RI "Private functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Usb device descriptors module\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
