.TH "USBD_DEF_Exported_Macros" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USBD_DEF_Exported_Macros \- USBD_DEF_Exported_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSWAPBYTE\fP(addr)"
.br
.ti -1c
.RI "#define \fBLOBYTE\fP(x)   ((uint8_t)((x) & 0x00FFU))"
.br
.ti -1c
.RI "#define \fBHIBYTE\fP(x)   ((uint8_t)(((x) & 0xFF00U) >> 8U))"
.br
.ti -1c
.RI "#define \fBMIN\fP(a,  b)   (((a) < (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBMAX\fP(a,  b)   (((a) > (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fB__ALIGN_END\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SWAPBYTE(addr)"
\fBValue:\fP
.PP
.nf
                               (((uint16_t)(*((uint8_t *)(addr)))) + \
                               (((uint16_t)(*(((uint8_t *)(addr)) + 1U))) << 8U))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
