.TH "vQueueDelete" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vQueueDelete \- vQueueDelete
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
queue\&. h 
.PP
.nf
void vQueueDelete( QueueHandle_t xQueue );
.fi
.PP
.PP
Delete a queue - freeing all the memory allocated for storing of items placed on the queue\&.
.PP
\fBParameters\fP
.RS 4
\fIxQueue\fP A handle to the queue to be deleted\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
