.TH "vSemaphoreDelete" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vSemaphoreDelete \- vSemaphoreDelete
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
semphr\&. h 
.PP
.nf
void vSemaphoreDelete( SemaphoreHandle_t xSemaphore );
.fi
.PP
.PP
Delete a semaphore\&. This function must be used with care\&. For example, do not delete a mutex type semaphore if the mutex is held by a task\&.
.PP
\fBParameters\fP
.RS 4
\fIxSemaphore\fP A handle to the semaphore to be deleted\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
