.TH "vTaskResume" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vTaskResume \- vTaskResume
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
task\&. h 
.PP
.nf
void vTaskResume( TaskHandle_t xTaskToResume );
.fi
.PP
.PP
INCLUDE_vTaskSuspend must be defined as 1 for this function to be available\&. See the configuration section for more information\&.
.PP
Resumes a suspended task\&.
.PP
A task that has been suspended by one or more calls to vTaskSuspend () will be made available for running again by a single call to vTaskResume ()\&.
.PP
\fBParameters\fP
.RS 4
\fIxTaskToResume\fP Handle to the task being readied\&.
.RE
.PP
Example usage: 
.PP
.nf

void vAFunction( void )
{
TaskHandle_t xHandle;

    // Create a task, storing the handle\&.
    xTaskCreate( vTaskCode, 'NAME', STACK_SIZE, NULL, tskIDLE_PRIORITY, &xHandle );

    // \&.\&.\&.

    // Use the handle to suspend the created task\&.
    vTaskSuspend( xHandle );

    // \&.\&.\&.

    // The created task will not run during this period, unless
    // another task calls vTaskResume( xHandle )\&.

    //\&.\&.\&.


    // Resume the suspended task ourselves\&.
    vTaskResume( xHandle );

    // The created task will once again get microcontroller processing
    // time in accordance with its priority within the system\&.
}
  
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
