.TH "xEventGroupCreate" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xEventGroupCreate \- xEventGroupCreate
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBevent_groups\&.h\fP 
.PP
.nf

EventGroupHandle_t xEventGroupCreate( void );
.fi
.PP
.PP
Create a new event group\&.
.PP
Internally, within the FreeRTOS implementation, event groups use a [small] block of memory, in which the event group's structure is stored\&. If an event groups is created using xEventGropuCreate() then the required memory is automatically dynamically allocated inside the xEventGroupCreate() function\&. (see http://www.freertos.org/a00111.html)\&. If an event group is created using xEventGropuCreateStatic() then the application writer must instead provide the memory that will get used by the event group\&. xEventGroupCreateStatic() therefore allows an event group to be created without using any dynamic memory allocation\&.
.PP
Although event groups are not related to ticks, for internal implementation reasons the number of bits available for use in an event group is dependent on the configUSE_16_BIT_TICKS setting in \fBFreeRTOSConfig\&.h\fP\&. If configUSE_16_BIT_TICKS is 1 then each event group contains 8 usable bits (bit 0 to bit 7)\&. If configUSE_16_BIT_TICKS is set to 0 then each event group has 24 usable bits (bit 0 to bit 23)\&. The EventBits_t type is used to store event bits within an event group\&.
.PP
\fBReturns\fP
.RS 4
If the event group was created then a handle to the event group is returned\&. If there was insufficient FreeRTOS heap available to create the event group then NULL is returned\&. See http://www.freertos.org/a00111.html
.RE
.PP
Example usage: 
.PP
.nf

   // Declare a variable to hold the created event group\&.
   EventGroupHandle_t xCreatedEventGroup;

   // Attempt to create the event group\&.
   xCreatedEventGroup = xEventGroupCreate();

   // Was the event group created successfully?
   if( xCreatedEventGroup == NULL )
   {
    // The event group was not created because there was insufficient
    // FreeRTOS heap available\&.
   }
   else
   {
    // The event group was created\&.
   }
  
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
