.TH "xEventGroupDefinition" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xEventGroupDefinition
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "EventBits_t \fBuxEventBits\fP"
.br
.ti -1c
.RI "\fBList_t\fP \fBxTasksWaitingForBits\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
