.TH "xMINI_LIST_ITEM" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xMINI_LIST_ITEM
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "listFIRST_LIST_ITEM_INTEGRITY_CHECK_VALUE configLIST_VOLATILE TickType_t \fBxItemValue\fP"
.br
.ti -1c
.RI "struct \fBxLIST_ITEM\fP *configLIST_VOLATILE \fBpxNext\fP"
.br
.ti -1c
.RI "struct \fBxLIST_ITEM\fP *configLIST_VOLATILE \fBpxPrevious\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
