.TH "xSTATIC_TCB" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xSTATIC_TCB
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpxDummy1\fP"
.br
.ti -1c
.RI "\fBStaticListItem_t\fP \fBxDummy3\fP [2]"
.br
.ti -1c
.RI "UBaseType_t \fBuxDummy5\fP"
.br
.ti -1c
.RI "void * \fBpxDummy6\fP"
.br
.ti -1c
.RI "uint8_t \fBucDummy7\fP [configMAX_TASK_NAME_LEN]"
.br
.ti -1c
.RI "uint32_t \fBulDummy18\fP"
.br
.ti -1c
.RI "uint8_t \fBucDummy19\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
