.TH "xTASK_STATUS" 3 "Mon May 24 2021" "gdmx-display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xTASK_STATUS
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TaskHandle_t \fBxHandle\fP"
.br
.ti -1c
.RI "const char * \fBpcTaskName\fP"
.br
.ti -1c
.RI "UBaseType_t \fBxTaskNumber\fP"
.br
.ti -1c
.RI "eTaskState \fBeCurrentState\fP"
.br
.ti -1c
.RI "UBaseType_t \fBuxCurrentPriority\fP"
.br
.ti -1c
.RI "UBaseType_t \fBuxBasePriority\fP"
.br
.ti -1c
.RI "uint32_t \fBulRunTimeCounter\fP"
.br
.ti -1c
.RI "StackType_t * \fBpxStackBase\fP"
.br
.ti -1c
.RI "uint16_t \fBusStackHighWaterMark\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gdmx-display from the source code\&.
